import { useEffect, useState } from "react";
import { Link } from "wouter";
import { AlertTriangle, CheckCircle2, Download, Eye, RefreshCw, RotateCcw, Search, XCircle } from "lucide-react";

type Health = {
  generatedAt:string; status:"healthy"|"review"|"attention";
  summary:{passed:number;review:number;failed:number};
  checks:{name:string;status:"pass"|"review"|"fail";detail:string}[];
  issues:{area:string;severity:string;title:string;detail:string;action?:string;href?:string}[];
  achievementReview:{playerId:number;playerName:string;achievementKey:string;achievementName:string;reason:string;reviewed:boolean;reviewedAt:string|null}[];
  activity:{formats:{name:string;matchesThisWeek:number;matchesLast14Days:number;quiet:boolean}[];totalThisWeek:number;inactivePlayers:{id:number;name:string;lastPlayed:string|null}[];titleLeaders:{id:number;name:string;points:number}[]};
  note:string;
};

const colors={pass:"#22c55e",review:"#ffd24a",fail:"#ff005c"};

export function IntegrityHealth(){
  const [data,setData]=useState<Health|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [reviewing,setReviewing]=useState("");
  const load=()=>{setLoading(true);setError("");fetch("/api/admin/integrity-health").then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error??"Health check failed");return r.json();}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
  const download=()=>{if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`tkdl-health-report-${data.generatedAt.slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);};
  const toggleReview=async(item:Health["achievementReview"][number])=>{const key=`${item.playerId}-${item.achievementKey}`;setReviewing(key);setError("");try{const response=await fetch("/api/admin/integrity-health/achievement-review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({playerId:item.playerId,achievementKey:item.achievementKey,reviewed:!item.reviewed})});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.error??"Could not update review");await load();}catch(e){setError(e instanceof Error?e.message:"Could not update review");}finally{setReviewing("");}};
  useEffect(load,[]);
  return <div className="p-5 space-y-5">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
      <div><h3 className="text-lg font-bold uppercase" style={{fontFamily:"Oswald, sans-serif"}}>League integrity report</h3><p className="text-sm text-white/40">Checks records, balances, season links, correction coverage and achievement evidence.</p></div>
      <div className="flex gap-2"><button onClick={download} disabled={!data} className="flex items-center gap-2 px-3 py-2 rounded-md text-xs font-bold uppercase disabled:opacity-40" style={{border:"1px solid rgba(255,255,255,.13)",color:"rgba(255,255,255,.7)"}}><Download size={14}/>Download report</button><button onClick={load} disabled={loading} className="flex items-center gap-2 px-3 py-2 rounded-md text-xs font-bold uppercase" style={{border:"1px solid rgba(255,255,255,.13)",color:"rgba(255,255,255,.7)"}}><RefreshCw size={14} className={loading?"animate-spin":""}/>Run checks</button></div>
    </div>
    {error&&<div className="rounded-lg p-3 text-sm" style={{border:"1px solid rgba(255,0,92,.3)",color:"#ff7aa8"}}>{error}</div>}
    {!data&&loading&&<div className="text-sm text-white/40">Inspecting league data…</div>}
    {data&&<>
      <div className="grid grid-cols-3 gap-3">
        {[{label:"Passed",value:data.summary.passed,color:colors.pass},{label:"Review",value:data.summary.review,color:colors.review},{label:"Problems",value:data.summary.failed,color:colors.fail}].map(x=><div key={x.label} className="rounded-lg p-3" style={{background:"rgba(255,255,255,.025)",border:`1px solid ${x.color}33`}}><strong className="text-2xl" style={{color:x.color,fontFamily:"Oswald, sans-serif"}}>{x.value}</strong><div className="text-[10px] uppercase tracking-widest text-white/40">{x.label}</div></div>)}
      </div>
      <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-2">{data.checks.map(c=>{const Icon=c.status==="pass"?CheckCircle2:c.status==="review"?AlertTriangle:XCircle;return <div key={c.name} className="rounded-lg p-3 flex gap-3" style={{background:"rgba(255,255,255,.025)",border:"1px solid rgba(255,255,255,.07)"}}><Icon size={18} style={{color:colors[c.status],flex:"0 0 auto"}}/><div><strong className="text-sm">{c.name}</strong><p className="text-xs text-white/40 mt-0.5">{c.detail}</p></div></div>})}</div>
      <section><h4 className="text-xs font-bold uppercase tracking-widest text-white/50 mb-2">League activity</h4><div className="grid md:grid-cols-3 gap-2">{data.activity.formats.map(x=><div key={x.name} className="rounded-lg p-3" style={{border:`1px solid ${x.quiet?"rgba(255,210,74,.22)":"rgba(34,197,94,.18)"}`,background:"rgba(255,255,255,.02)"}}><div className="text-xs font-bold">{x.name}</div><strong className="text-2xl" style={{fontFamily:"Oswald, sans-serif",color:x.quiet?"#ffd24a":"#22c55e"}}>{x.matchesThisWeek}</strong><div className="text-[10px] uppercase tracking-wider text-white/30">matches this week</div><p className="text-[11px] text-white/35 mt-1">{x.quiet?"No results in 14 days":`${x.matchesLast14Days} in the last 14 days`}</p></div>)}</div>
        {data.activity.titleLeaders.length>1&&<div className="mt-2 rounded-lg p-3 text-sm" style={{border:"1px solid rgba(168,85,247,.24)",color:"#d8b4fe"}}>Title race tied on {data.activity.titleLeaders[0].points} points: {data.activity.titleLeaders.map((x,i)=><span key={x.id}>{i>0&&", "}<Link href={`/players/${x.id}`} className="underline underline-offset-2">{x.name}</Link></span>)}</div>}
        {data.activity.inactivePlayers.length>0&&<div className="mt-2 rounded-lg p-3" style={{border:"1px solid rgba(255,210,74,.18)"}}><strong className="text-xs uppercase tracking-wider" style={{color:"#ffd24a"}}>No Singles/team appearance for 21 days</strong><p className="text-xs text-white/40 mt-1">{data.activity.inactivePlayers.map((x,i)=><span key={x.id}>{i>0&&", "}<Link href={`/players/${x.id}`} className="underline underline-offset-2">{x.name}</Link></span>)}</p></div>}
      </section>
      {data.issues.length>0&&<section><h4 className="text-xs font-bold uppercase tracking-widest text-white/50 mb-2">Problems found</h4><div className="space-y-2">{data.issues.map((x,i)=><div key={i} className="rounded-lg px-3 py-2" style={{border:`1px solid ${x.severity==="error"?colors.fail:colors.review}33`,background:"rgba(255,255,255,.02)"}}><div className="text-[10px] uppercase tracking-widest" style={{color:x.severity==="error"?colors.fail:colors.review}}>{x.area}</div><strong className="text-sm">{x.title}</strong><p className="text-xs text-white/40">{x.detail}</p>{x.action&&<p className="text-xs text-white/60 mt-1"><span className="font-bold text-white/75">Recommended:</span> {x.action}</p>}{x.href&&<Link href={x.href} className="inline-flex mt-2 text-[10px] font-bold uppercase tracking-wider" style={{color:"#a855f7"}}>Open details →</Link>}</div>)}</div></section>}
      {data.issues.length===0&&<div className="rounded-lg p-3 flex items-center gap-2 text-sm" style={{border:"1px solid rgba(34,197,94,.2)",color:"#86efac"}}><CheckCircle2 size={16}/>No record, balance, season, or match-link problems found.</div>}
      <section><div className="flex items-center gap-2 mb-2"><Search size={14} style={{color:"#a855f7"}}/><h4 className="text-xs font-bold uppercase tracking-widest text-white/50">Achievement integrity checker</h4></div>{data.achievementReview.length===0?<div className="rounded-lg p-3 text-sm text-white/50" style={{border:"1px solid rgba(34,197,94,.2)"}}>No Doubles milestone badges need review.</div>:<div className="space-y-2">{data.achievementReview.map(x=>{const key=`${x.playerId}-${x.achievementKey}`;return <div key={key} className="rounded-lg p-3" style={{border:`1px solid ${x.reviewed?"rgba(34,197,94,.22)":"rgba(255,210,74,.22)"}`,background:x.reviewed?"rgba(34,197,94,.025)":"rgba(255,210,74,.025)",opacity:x.reviewed?.78:1}}><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2"><div><div className="flex items-center gap-2"><strong className="text-sm">{x.playerName} · {x.achievementName}</strong>{x.reviewed&&<span className="text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded" style={{color:"#22c55e",background:"rgba(34,197,94,.1)"}}>Reviewed</span>}</div><p className="text-xs text-white/45 mt-1">{x.reason}</p>{x.reviewedAt&&<p className="text-[10px] text-white/30 mt-1">Checked {new Date(x.reviewedAt).toLocaleString()}</p>}</div><div className="flex gap-2 shrink-0"><Link href={`/players/${x.playerId}`} className="inline-flex items-center gap-1 px-2 py-1.5 rounded text-[10px] font-bold uppercase" style={{border:"1px solid rgba(255,255,255,.12)",color:"rgba(255,255,255,.65)"}}><Eye size={12}/>Player</Link><button onClick={()=>toggleReview(x)} disabled={reviewing===key} className="inline-flex items-center gap-1 px-2 py-1.5 rounded text-[10px] font-bold uppercase disabled:opacity-40" style={{border:`1px solid ${x.reviewed?"rgba(255,255,255,.12)":"rgba(34,197,94,.25)"}`,color:x.reviewed?"rgba(255,255,255,.6)":"#22c55e"}}>{x.reviewed?<><RotateCcw size={12}/>Reopen</>:<><CheckCircle2 size={12}/>Mark reviewed</>}</button></div></div></div>})}</div>}<p className="text-[11px] text-white/30 mt-2">{data.note} Marking a flag reviewed records that an admin checked it; it does not remove the badge or reclaim a reward.</p></section>
    </>}
  </div>;
}
