import { useCallback, useEffect, useState } from "react";
import { Activity, BellRing, CheckCircle2, Clock3, Database, RefreshCw, Users, XCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiFetchJson } from "@/lib/api-fetch";
import { CollapsibleAdminSection } from "./collapsible-section";

type Operations = {
  generatedAt:string; database:string; londonNow:string;
  seasonAutomation:{lastCheckedAt:string|null;lastSucceededAt:string|null;lastError:string|null;schedule:string};
  seasons:{id:number;name:string;leagueType:string;startDate:string;currentMonth:boolean}[];
  notificationQueue:{pending:number;due:number;retrying:number;oldestPending:string|null;lastAttempt:string|null;lastError:string|null};
  doubles:{seasonId:number|null;teamCount:number;threePlayerTeams:number;defendingTeam:string|null;defendingPairAvailable:boolean;defendingPairKept:boolean|null};
  resetLocks:{leagueType:string;lockedAt:string}[];
  lastAdminAction:{action:string;created_at:string}|null;
};
type SeasonPreview={generatedAt:string;nextSeasonName:string;writesPerformed:boolean;singles:{activePlayers:number;leaders:{id:number;name:string;points:number;elo:number}[];blockedByTie:boolean;effect:string};doubles:{champion:string|null;championPoints:number|null;activePlayers:number;nextTeamCount:number;createsThreePlayerTeam:boolean;defendingPairKept:boolean;effect:string};shiftWars:{champion:string|null;teams:{id:number;name:string;currentPoints:number;resetTo:number}[];effect:string}};

export function OperationsDashboard(){
  const [data,setData]=useState<Operations|null>(null);
  const [loading,setLoading]=useState(false);
  const [busy,setBusy]=useState<"push"|"season"|null>(null);
  const [error,setError]=useState("");
  const [preview,setPreview]=useState<SeasonPreview|null>(null);
  const [previewing,setPreviewing]=useState(false);
  const {toast}=useToast();
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await apiFetchJson<Operations>("/api/admin/operations"));}catch(e){setError(e instanceof Error?e.message:"Could not load operations");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const action=async(kind:"push"|"season")=>{setBusy(kind);try{const url=kind==="push"?"/api/admin/operations/retry-notifications":"/api/admin/operations/run-season-check";const result=await apiFetchJson<any>(url,{method:"POST"});toast({title:kind==="push"?`Notification retry complete`:"Season check complete",description:kind==="push"?`${result.delivered??0} delivered · ${result.failed??0} still waiting`:"All three competitions checked"});await load();}catch(e){toast({title:"Operation failed",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}finally{setBusy(null);}};
  const loadPreview=async()=>{setPreviewing(true);try{setPreview(await apiFetchJson<SeasonPreview>("/api/admin/operations/season-preview"));}catch(e){toast({title:"Preview failed",description:e instanceof Error?e.message:"Please try again",variant:"destructive"});}finally{setPreviewing(false);}};
  const healthySeasons=Boolean(data&&["singles","doubles","shift_wars"].every(type=>data.seasons.filter(x=>x.leagueType===type&&x.currentMonth).length===1));
  return <CollapsibleAdminSection sectionId="operations" defaultOpen title="Operations Centre" icon={Activity} accent="#22c55e" borderColor="rgba(34,197,94,.24)" background="rgba(34,197,94,.025)" badge={data&&<span className="text-[10px] font-bold uppercase" style={{color:error?"#ff005c":healthySeasons?"#22c55e":"#ffd24a"}}>{error?"Needs attention":healthySeasons?"Systems ready":"Review"}</span>}>
    <div className="p-4 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div><h3 className="font-bold uppercase" style={{fontFamily:"Oswald, sans-serif"}}>League operations</h3><p className="text-xs text-white/40">Live status for season automation, the Doubles draw and notification delivery.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 px-3 py-2 rounded text-xs font-bold uppercase disabled:opacity-40" style={{border:"1px solid rgba(255,255,255,.12)",color:"rgba(255,255,255,.65)"}}><RefreshCw className={`w-3.5 h-3.5 ${loading?"animate-spin":""}`}/>Refresh</button></div>
      {error&&<div className="rounded-lg p-3 text-sm" style={{border:"1px solid rgba(255,0,92,.3)",color:"#ff7aa8"}}>{error}</div>}
      {data&&<>
        <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-2">
          <Status icon={Database} label="Database" value="Online" ok />
          <Status icon={Clock3} label="Season automation" value={healthySeasons?"Current month":"Review required"} ok={healthySeasons}/>
          <Status icon={Users} label="Doubles draw" value={data.doubles.teamCount?`${data.doubles.teamCount} teams live`:"Waiting for draw"} ok={data.doubles.teamCount>0}/>
          <Status icon={BellRing} label="Push delivery" value={data.notificationQueue.pending?`${data.notificationQueue.pending} waiting`:`Queue clear`} ok={data.notificationQueue.due===0}/>
        </div>
        <div className="grid lg:grid-cols-3 gap-3">
          <Panel title="Current seasons">{data.seasons.map(s=><div key={s.id} className="flex justify-between gap-3 text-xs py-1"><span className="capitalize text-white/65">{s.leagueType.replace("_"," ")}</span><span style={{color:s.currentMonth?"#22c55e":"#ffd24a"}}>{s.name} · {s.startDate}</span></div>)}<p className="text-[10px] text-white/30 mt-2">{data.seasonAutomation.lastSucceededAt?`Last automation check passed ${new Date(data.seasonAutomation.lastSucceededAt).toLocaleString()}.`:"No completed automation check recorded since this server woke."} {data.seasonAutomation.schedule}.</p>{data.seasonAutomation.lastError&&<p className="text-[11px] mt-1" style={{color:"#ff7aa8"}}>{data.seasonAutomation.lastError}</p>}{data.resetLocks.length>0&&<p className="text-[11px] mt-2" style={{color:"#ffd24a"}}>Reset currently running: {data.resetLocks.map(x=>x.leagueType).join(", ")}</p>}</Panel>
          <Panel title="Doubles draw"><p className="text-xs text-white/55">{data.doubles.threePlayerTeams>0?`${data.doubles.threePlayerTeams} three-player team created for the odd roster.`:"Every current team has two players."}</p>{data.doubles.defendingTeam&&<p className="text-xs mt-2" style={{color:data.doubles.defendingPairKept===false?"#ffd24a":"#86efac"}}>{data.doubles.defendingPairAvailable?(data.doubles.defendingPairKept?`${data.doubles.defendingTeam} stayed together to defend their title.`:`${data.doubles.defendingTeam} were eligible to defend but are not paired.`):`${data.doubles.defendingTeam} was a three-player champion team, so no pair was retained.`}</p>}</Panel>
          <Panel title="Notification queue"><div className="grid grid-cols-3 gap-2 text-center"><Metric label="Pending" value={data.notificationQueue.pending}/><Metric label="Due" value={data.notificationQueue.due}/><Metric label="Retrying" value={data.notificationQueue.retrying}/></div>{data.notificationQueue.oldestPending&&<p className="text-[10px] text-white/30 mt-2">Oldest waiting since {new Date(data.notificationQueue.oldestPending).toLocaleString()}.</p>}{data.notificationQueue.lastError&&<p className="text-[11px] mt-2 truncate" title={data.notificationQueue.lastError} style={{color:"#ff9abb"}}>Latest error: {data.notificationQueue.lastError}</p>}</Panel>
        </div>
        <div className="flex flex-col sm:flex-row gap-2"><button onClick={()=>void loadPreview()} disabled={previewing} className="px-4 py-2 rounded text-xs font-bold uppercase disabled:opacity-40" style={{background:"rgba(168,85,247,.09)",border:"1px solid rgba(168,85,247,.24)",color:"#c084fc"}}>{previewing?"Building preview…":"Preview next rollover"}</button><button onClick={()=>void action("season")} disabled={busy!==null} className="px-4 py-2 rounded text-xs font-bold uppercase disabled:opacity-40" style={{background:"rgba(255,210,74,.09)",border:"1px solid rgba(255,210,74,.24)",color:"#ffd24a"}}>{busy==="season"?"Checking…":"Run safe season check"}</button><button onClick={()=>void action("push")} disabled={busy!==null||data.notificationQueue.due===0} className="px-4 py-2 rounded text-xs font-bold uppercase disabled:opacity-40" style={{background:"rgba(56,189,248,.09)",border:"1px solid rgba(56,189,248,.24)",color:"#38bdf8"}}>{busy==="push"?"Retrying…":"Retry due notifications"}</button></div>
        {preview&&<div className="rounded-xl p-3 sm:p-4 space-y-3" style={{background:"rgba(168,85,247,.045)",border:"1px solid rgba(168,85,247,.2)"}}><div className="flex flex-wrap justify-between gap-2"><div><h4 className="font-bold uppercase text-sm" style={{fontFamily:"Oswald, sans-serif",color:"#d8b4fe"}}>Dry run · {preview.nextSeasonName}</h4><p className="text-[11px] text-white/35">Read-only preview — no season, team or score was changed.</p></div><button onClick={()=>setPreview(null)} className="text-xs text-white/35">Close</button></div><div className="grid md:grid-cols-3 gap-2"><PreviewPanel title="Singles"><p>{preview.singles.blockedByTie?`Blocked: ${preview.singles.leaders.map(x=>x.name).join(" and ")} are tied on ${preview.singles.leaders[0]?.points} points.`:`Champion: ${preview.singles.leaders[0]?.name??"No eligible player"}.`}</p><p>{preview.singles.activePlayers} active players reset to 25.</p></PreviewPanel><PreviewPanel title="Doubles"><p>Champion: {preview.doubles.champion??"No completed table"}.</p><p>{preview.doubles.nextTeamCount} teams in the next draw{preview.doubles.createsThreePlayerTeam?", including one three-player team":""}.</p>{preview.doubles.champion&&<p>{preview.doubles.defendingPairKept?"The champion pair stays together.":"No defending pair will be retained."}</p>}</PreviewPanel><PreviewPanel title="Shift Wars"><p>Champion: {preview.shiftWars.champion??"No teams"}.</p>{preview.shiftWars.teams.map(team=><p key={team.id}>{team.name}: {team.currentPoints} → {team.resetTo}</p>)}</PreviewPanel></div></div>}
      </>}
    </div>
  </CollapsibleAdminSection>;
}

function Status({icon:Icon,label,value,ok}:{icon:any;label:string;value:string;ok:boolean}){const Mark=ok?CheckCircle2:XCircle;return <div className="rounded-lg p-3" style={{background:"rgba(255,255,255,.025)",border:`1px solid ${ok?"rgba(34,197,94,.18)":"rgba(255,210,74,.22)"}`}}><div className="flex items-center justify-between"><Icon className="w-4 h-4 text-white/35"/><Mark className="w-4 h-4" style={{color:ok?"#22c55e":"#ffd24a"}}/></div><div className="text-[10px] uppercase tracking-widest text-white/30 mt-2">{label}</div><strong className="text-sm" style={{color:ok?"#d1fae5":"#fde68a"}}>{value}</strong></div>}
function Panel({title,children}:{title:string;children:any}){return <div className="rounded-lg p-3" style={{background:"rgba(255,255,255,.02)",border:"1px solid rgba(255,255,255,.07)"}}><h4 className="text-[11px] font-bold uppercase tracking-widest text-white/40 mb-2">{title}</h4>{children}</div>}
function Metric({label,value}:{label:string;value:number}){return <div><strong className="text-xl" style={{fontFamily:"Oswald, sans-serif"}}>{value}</strong><div className="text-[9px] uppercase text-white/30">{label}</div></div>}
function PreviewPanel({title,children}:{title:string;children:any}){return <div className="rounded-lg p-3 text-xs space-y-1 text-white/55" style={{background:"rgba(0,0,0,.16)",border:"1px solid rgba(255,255,255,.07)"}}><strong className="block uppercase tracking-wider mb-1" style={{fontFamily:"Oswald, sans-serif",color:"#fff"}}>{title}</strong>{children}</div>}
