// COMPLETE ACHIEVEMENT REWARDS MAPPING
// Generated from all achievement definition files
// 534 achievements total

export const ACHIEVEMENT_REWARDS: Record<
  string,
  { coinReward?: number; packReward?: 'SINGLE' | 'FIVE' | 'TEN' }
> = {
  ALL_IN_WIN: { coinReward: 50, packReward: "SINGLE" },
  APOCALYPSE: { coinReward: 400, packReward: "TEN" },
  ASCENDED: { coinReward: 500, packReward: "TEN" },
  ASSASSIN: { coinReward: 100, packReward: "SINGLE" },
  BACK_TO_BACK_TITLE: { coinReward: 200, packReward: "FIVE" },
  BLOOD_HUNTER: { coinReward: 250, packReward: "TEN" },
  BOT_100K_SCORE: { coinReward: 125, packReward: "FIVE" },
  BOT_100_180S: { coinReward: 150, packReward: "SINGLE" },
  BOT_100_DARTS: { coinReward: 20 },
  BOT_100_FINISHES: { coinReward: 175, packReward: "FIVE" },
  BOT_100_SESSIONS: { coinReward: 200, packReward: "SINGLE" },
  BOT_10K_SCORE: { coinReward: 60, packReward: "SINGLE" },
  BOT_10M_SCORE: { coinReward: 600, packReward: "TEN" },
  BOT_15K_DARTS: { coinReward: 100, packReward: "FIVE" },
  BOT_180_10K: { coinReward: 750, packReward: "TEN" },
  BOT_180_15: { coinReward: 75, packReward: "SINGLE" },
  BOT_180_150: { coinReward: 125, packReward: "SINGLE" },
  BOT_180_1K: { coinReward: 1000, packReward: "TEN" },
  BOT_180_2: { coinReward: 25 },
  BOT_180_20: { coinReward: 80, packReward: "SINGLE" },
  BOT_180_200: { coinReward: 300, packReward: "FIVE" },
  BOT_180_25: { coinReward: 100, packReward: "SINGLE" },
  BOT_180_2K: { coinReward: 400, packReward: "TEN" },
  BOT_180_3: { coinReward: 30 },
  BOT_180_30: { coinReward: 50, packReward: "SINGLE" },
  BOT_180_300: { coinReward: 350, packReward: "TEN" },
  BOT_180_5: { coinReward: 35 },
  BOT_180_5K: { coinReward: 500, packReward: "TEN" },
  BOT_180_7: { coinReward: 40 },
  BOT_180_75: { coinReward: 150, packReward: "FIVE" },
  BOT_180_750: { coinReward: 600, packReward: "TEN" },
  BOT_1M_SCORE: { coinReward: 400, packReward: "FIVE" },
  BOT_200_SESSIONS: { coinReward: 175, packReward: "SINGLE" },
  BOT_20_SESSIONS: { coinReward: 60, packReward: "SINGLE" },
  BOT_25_FINISHES: { coinReward: 75, packReward: "SINGLE" },
  BOT_2K_DARTS: { coinReward: 80, packReward: "SINGLE" },
  BOT_500_180S: { coinReward: 200, packReward: "TEN" },
  BOT_500_DARTS: { coinReward: 20 },
  BOT_500_FINISHES: { coinReward: 250, packReward: "FIVE" },
  BOT_50K_DARTS: { coinReward: 300, packReward: "TEN" },
  BOT_50_180S: { coinReward: 200, packReward: "FIVE" },
  BOT_50_SESSIONS: { coinReward: 100, packReward: "SINGLE" },
  BOT_5K_DARTS: { coinReward: 50, packReward: "SINGLE" },
  BOT_5M_SCORE: { coinReward: 750, packReward: "TEN" },
  BOT_5_SESSIONS: { coinReward: 25 },
  BOT_ACC_10: { coinReward: 30 },
  BOT_ACC_15: { coinReward: 35 },
  BOT_ACC_20: { coinReward: 40 },
  BOT_ACC_25: { coinReward: 60, packReward: "SINGLE" },
  BOT_ACC_30: { coinReward: 75, packReward: "SINGLE" },
  BOT_ACC_40: { coinReward: 80, packReward: "SINGLE" },
  BOT_ACC_5: { coinReward: 20 },
  BOT_ACC_50: { coinReward: 100, packReward: "SINGLE" },
  BOT_ACC_60: { coinReward: 125, packReward: "FIVE" },
  BOT_ACC_70: { coinReward: 150, packReward: "SINGLE" },
  BOT_ACC_75: { coinReward: 175, packReward: "FIVE" },
  BOT_ACC_80: { coinReward: 350, packReward: "FIVE" },
  BOT_ACC_85: { coinReward: 400, packReward: "TEN" },
  BOT_ACC_90: { coinReward: 1000, packReward: "TEN" },
  BOT_ACC_95: { coinReward: 400, packReward: "TEN" },
  BOT_ALL_ROUNDER: { coinReward: 100, packReward: "SINGLE" },
  BOT_AMATEUR: { coinReward: 25 },
  BOT_BOOTS_UP: { coinReward: 30 },
  BOT_CA_1: { coinReward: 35 },
  BOT_CA_10: { coinReward: 40 },
  BOT_CA_100: { coinReward: 50, packReward: "SINGLE" },
  BOT_CA_150: { coinReward: 200, packReward: "SINGLE" },
  BOT_CA_1K: { coinReward: 200, packReward: "FIVE" },
  BOT_CA_20: { coinReward: 20 },
  BOT_CA_200: { coinReward: 100, packReward: "FIVE" },
  BOT_CA_2500: { coinReward: 500, packReward: "TEN" },
  BOT_CA_30: { coinReward: 60, packReward: "SINGLE" },
  BOT_CA_300: { coinReward: 125, packReward: "SINGLE" },
  BOT_CA_5: { coinReward: 25 },
  BOT_CA_50: { coinReward: 75, packReward: "SINGLE" },
  BOT_CA_500: { coinReward: 250, packReward: "TEN" },
  BOT_CA_5K: { coinReward: 600, packReward: "TEN" },
  BOT_CA_75: { coinReward: 80, packReward: "SINGLE" },
  BOT_CH_10: { coinReward: 30 },
  BOT_CH_10K: { coinReward: 750, packReward: "TEN" },
  BOT_CH_15: { coinReward: 100, packReward: "SINGLE" },
  BOT_CH_150: { coinReward: 150, packReward: "FIVE" },
  BOT_CH_1K: { coinReward: 300, packReward: "FIVE" },
  BOT_CH_2: { coinReward: 35 },
  BOT_CH_20: { coinReward: 50, packReward: "SINGLE" },
  BOT_CH_200: { coinReward: 175, packReward: "SINGLE" },
  BOT_CH_2K: { coinReward: 1000, packReward: "TEN" },
  BOT_CH_3: { coinReward: 40 },
  BOT_CH_30: { coinReward: 60, packReward: "SINGLE" },
  BOT_CH_300: { coinReward: 350, packReward: "TEN" },
  BOT_CH_5: { coinReward: 20 },
  BOT_CH_50: { coinReward: 75, packReward: "SINGLE" },
  BOT_CH_5K: { coinReward: 400, packReward: "TEN" },
  BOT_CH_7: { coinReward: 25 },
  BOT_CH_75: { coinReward: 200, packReward: "FIVE" },
  BOT_CH_750: { coinReward: 400, packReward: "FIVE" },
  BOT_CLUB: { coinReward: 80, packReward: "SINGLE" },
  BOT_COUNTY: { coinReward: 100, packReward: "SINGLE" },
  BOT_D_100K: { coinReward: 200, packReward: "TEN" },
  BOT_D_10K: { coinReward: 125, packReward: "FIVE" },
  BOT_D_1250: { coinReward: 100, packReward: "SINGLE" },
  BOT_D_12500: { coinReward: 150, packReward: "SINGLE" },
  BOT_D_150: { coinReward: 30 },
  BOT_D_1500: { coinReward: 50, packReward: "SINGLE" },
  BOT_D_1K: { coinReward: 60, packReward: "SINGLE" },
  BOT_D_1M: { coinReward: 500, packReward: "TEN" },
  BOT_D_200: { coinReward: 35 },
  BOT_D_20K: { coinReward: 175, packReward: "FIVE" },
  BOT_D_25: { coinReward: 40 },
  BOT_D_250: { coinReward: 20 },
  BOT_D_2500: { coinReward: 75, packReward: "SINGLE" },
  BOT_D_250K: { coinReward: 600, packReward: "TEN" },
  BOT_D_25K: { coinReward: 250, packReward: "FIVE" },
  BOT_D_300: { coinReward: 25 },
  BOT_D_35K: { coinReward: 300, packReward: "TEN" },
  BOT_D_3K: { coinReward: 80, packReward: "SINGLE" },
  BOT_D_400: { coinReward: 30 },
  BOT_D_4K: { coinReward: 100, packReward: "SINGLE" },
  BOT_D_50: { coinReward: 35 },
  BOT_D_500K: { coinReward: 750, packReward: "TEN" },
  BOT_D_5M: { coinReward: 1000, packReward: "TEN" },
  BOT_D_600: { coinReward: 40 },
  BOT_D_6K: { coinReward: 200, packReward: "SINGLE" },
  BOT_D_750: { coinReward: 20 },
  BOT_D_7500: { coinReward: 100, packReward: "FIVE" },
  BOT_D_75K: { coinReward: 350, packReward: "FIVE" },
  BOT_ELITE: { coinReward: 400, packReward: "TEN" },
  BOT_FIRST_180: { coinReward: 25 },
  BOT_FIRST_FINISH: { coinReward: 30 },
  BOT_FIRST_SESSION: { coinReward: 35 },
  BOT_FORMAT_MASTER: { coinReward: 125, packReward: "SINGLE" },
  BOT_GM_1: { coinReward: 40 },
  BOT_GM_10: { coinReward: 50, packReward: "SINGLE" },
  BOT_GM_15: { coinReward: 150, packReward: "FIVE" },
  BOT_GM_2: { coinReward: 20 },
  BOT_GM_25: { coinReward: 175, packReward: "SINGLE" },
  BOT_GM_30: { coinReward: 200, packReward: "FIVE" },
  BOT_GM_40: { coinReward: 400, packReward: "TEN" },
  BOT_GM_5: { coinReward: 25 },
  BOT_GM_50: { coinReward: 200, packReward: "FIVE" },
  BOT_GM_62: { coinReward: 250, packReward: "TEN" },
  BOT_GM_ALL: { coinReward: 500, packReward: "TEN" },
  BOT_POLYMATH: { coinReward: 60, packReward: "SINGLE" },
  BOT_PRO: { coinReward: 300, packReward: "FIVE" },
  BOT_SC_100: { coinReward: 30 },
  BOT_SC_100M: { coinReward: 600, packReward: "TEN" },
  BOT_SC_1500: { coinReward: 35 },
  BOT_SC_150K: { coinReward: 100, packReward: "SINGLE" },
  BOT_SC_15K: { coinReward: 75, packReward: "SINGLE" },
  BOT_SC_1B: { coinReward: 750, packReward: "TEN" },
  BOT_SC_1K: { coinReward: 40 },
  BOT_SC_250: { coinReward: 20 },
  BOT_SC_2500: { coinReward: 25 },
  BOT_SC_2500K: { coinReward: 350, packReward: "TEN" },
  BOT_SC_250K: { coinReward: 400, packReward: "FIVE" },
  BOT_SC_25K: { coinReward: 125, packReward: "FIVE" },
  BOT_SC_25M: { coinReward: 1000, packReward: "TEN" },
  BOT_SC_2K: { coinReward: 30 },
  BOT_SC_3K: { coinReward: 80, packReward: "SINGLE" },
  BOT_SC_500: { coinReward: 35 },
  BOT_SC_500K: { coinReward: 200, packReward: "TEN" },
  BOT_SC_500M: { coinReward: 400, packReward: "TEN" },
  BOT_SC_50K: { coinReward: 150, packReward: "SINGLE" },
  BOT_SC_50M: { coinReward: 500, packReward: "TEN" },
  BOT_SC_5K: { coinReward: 100, packReward: "SINGLE" },
  BOT_SC_7500: { coinReward: 50, packReward: "SINGLE" },
  BOT_SC_75K: { coinReward: 175, packReward: "FIVE" },
  BOT_S_10: { coinReward: 40 },
  BOT_S_1000: { coinReward: 600, packReward: "TEN" },
  BOT_S_12: { coinReward: 20 },
  BOT_S_125: { coinReward: 200, packReward: "SINGLE" },
  BOT_S_15: { coinReward: 25 },
  BOT_S_150: { coinReward: 100, packReward: "FIVE" },
  BOT_S_1500: { coinReward: 750, packReward: "TEN" },
  BOT_S_175: { coinReward: 125, packReward: "SINGLE" },
  BOT_S_2: { coinReward: 30 },
  BOT_S_2000: { coinReward: 1000, packReward: "TEN" },
  BOT_S_25: { coinReward: 60, packReward: "SINGLE" },
  BOT_S_250: { coinReward: 250, packReward: "FIVE" },
  BOT_S_3: { coinReward: 35 },
  BOT_S_30: { coinReward: 75, packReward: "SINGLE" },
  BOT_S_300: { coinReward: 300, packReward: "TEN" },
  BOT_S_40: { coinReward: 80, packReward: "SINGLE" },
  BOT_S_400: { coinReward: 350, packReward: "FIVE" },
  BOT_S_500: { coinReward: 400, packReward: "TEN" },
  BOT_S_60: { coinReward: 100, packReward: "SINGLE" },
  BOT_S_7: { coinReward: 40 },
  BOT_S_75: { coinReward: 50, packReward: "SINGLE" },
  BOT_S_750: { coinReward: 400, packReward: "TEN" },
  BOT_TEN_180S: { coinReward: 60, packReward: "SINGLE" },
  BOT_VERSATILE: { coinReward: 20 },
  BREAKTHROUGH: { coinReward: 200, packReward: "FIVE" },
  BRONZE_BLOODED: { coinReward: 25 },
  BULLSEYE: { coinReward: 75, packReward: "SINGLE" },
  CC_COLLECTOR_10: { coinReward: 30 },
  CC_COLLECTOR_25: { coinReward: 80, packReward: "SINGLE" },
  CC_COLLECTOR_50: { coinReward: 150, packReward: "FIVE" },
  CC_COLLECTOR_ALL: { coinReward: 250, packReward: "TEN" },
  CC_FIRST_MATCH: { coinReward: 35 },
  CC_FIRST_WIN: { coinReward: 40 },
  CC_LEGENDARY_CARD: { coinReward: 100, packReward: "SINGLE" },
  CC_PACKS_10: { coinReward: 50, packReward: "SINGLE" },
  CC_PACKS_25: { coinReward: 175, packReward: "SINGLE" },
  CC_PACKS_5: { coinReward: 20 },
  CC_PACK_OPENER: { coinReward: 25 },
  CC_STREAK_3: { coinReward: 30 },
  CC_STREAK_30: { coinReward: 200, packReward: "FIVE" },
  CC_STREAK_7: { coinReward: 60, packReward: "SINGLE" },
  CC_WIN_10: { coinReward: 75, packReward: "SINGLE" },
  CC_WIN_25: { coinReward: 100, packReward: "SINGLE" },
  CC_WIN_5: { coinReward: 35 },
  CC_WIN_50: { coinReward: 300, packReward: "FIVE" },
  CENTURY_POINTS: { coinReward: 40 },
  CHAOS_AGENT: { coinReward: 350, packReward: "TEN" },
  CLIMBER: { coinReward: 20 },
  COLD_SNAP: { coinReward: 80, packReward: "SINGLE" },
  COLLAPSING: { coinReward: 100, packReward: "SINGLE" },
  COLLECTOR: { coinReward: 50, packReward: "SINGLE" },
  COMEBACK_KING: { coinReward: 125, packReward: "FIVE" },
  COMPLETE_COLLECTOR: { coinReward: 150, packReward: "SINGLE" },
  CONQUEROR: { coinReward: 175, packReward: "FIVE" },
  CONQUISTADOR: { coinReward: 400, packReward: "FIVE" },
  CONSISTENT_ELITE: { coinReward: 200, packReward: "TEN" },
  CRICKET_KING: { coinReward: 60, packReward: "SINGLE" },
  CROWNED: { coinReward: 250, packReward: "FIVE" },
  DECORATED: { coinReward: 300, packReward: "TEN" },
  DETONATOR: { coinReward: 200, packReward: "SINGLE" },
  DOUBLED_DOWN: { coinReward: 100, packReward: "FIVE" },
  DOUBLE_TROUBLE: { coinReward: 75, packReward: "SINGLE" },
  DUELIST: { coinReward: 25 },
  DYNASTY: { coinReward: 500, packReward: "TEN" },
  ELIMINATOR: { coinReward: 125, packReward: "SINGLE" },
  ELO_1050: { coinReward: 80, packReward: "SINGLE" },
  ELO_1200: { coinReward: 150, packReward: "FIVE" },
  ELO_1300: { coinReward: 350, packReward: "FIVE" },
  FIGHTER: { coinReward: 30 },
  FIRST_BLOOD: { coinReward: 35 },
  FIRST_BLOOD_SEASON: { coinReward: 100, packReward: "SINGLE" },
  FIVE_O_ONE: { coinReward: 50, packReward: "SINGLE" },
  FORTRESS: { coinReward: 175, packReward: "SINGLE" },
  FORTRESS_KING: { coinReward: 200, packReward: "FIVE" },
  FREEFALL: { coinReward: 60, packReward: "SINGLE" },
  FROZEN_OUT: { coinReward: 100, packReward: "SINGLE" },
  GAMBLER: { coinReward: 75, packReward: "SINGLE" },
  GAME_HOPPER_10: { coinReward: 125, packReward: "FIVE" },
  GAME_HOPPER_20: { coinReward: 400, packReward: "TEN" },
  GENIUS: { coinReward: 150, packReward: "SINGLE" },
  GHOST: { coinReward: 80, packReward: "SINGLE" },
  GIANT_KILLER: { coinReward: 175, packReward: "FIVE" },
  GOLDEN_ERA: { coinReward: 200, packReward: "SINGLE" },
  GRAVE_DIGGER: { coinReward: 100, packReward: "FIVE" },
  HALL_OF_FAME: { coinReward: 600, packReward: "TEN" },
  HEAT_CHECK: { coinReward: 40 },
  HIGH_ROLLER: { coinReward: 100, packReward: "SINGLE" },
  HIGH_STAKES_LIFE: { coinReward: 125, packReward: "SINGLE" },
  HISTORIAN: { coinReward: 50, packReward: "SINGLE" },
  HOT_HAND: { coinReward: 150, packReward: "FIVE" },
  HOT_STREAK: { coinReward: 175, packReward: "SINGLE" },
  ICE_COLD: { coinReward: 200, packReward: "FIVE" },
  IMMORTAL: { coinReward: 250, packReward: "TEN" },
  INFERNO: { coinReward: 300, packReward: "FIVE" },
  IRON_WALL: { coinReward: 200, packReward: "FIVE" },
  JACK_OF_ALL: { coinReward: 350, packReward: "TEN" },
  JUNE_WARRIOR: { coinReward: 20 },
  KILBIRNIE_LION: { coinReward: 100, packReward: "SINGLE" },
  KING_SLAYER: { coinReward: 125, packReward: "FIVE" },
  LAST_MAN_STANDING: { coinReward: 750, packReward: "TEN" },
  LEGEND: { coinReward: 1000, packReward: "TEN" },
  LONE_WOLF: { coinReward: 150, packReward: "SINGLE" },
  LUCKY_SOB_MASSIVE: { coinReward: 175, packReward: "FIVE" },
  LUNCH_LEGEND: { coinReward: 60, packReward: "SINGLE" },
  M501_180_FIFTY: { coinReward: 400, packReward: "FIVE" },
  M501_180_FIVE: { coinReward: 75, packReward: "SINGLE" },
  M501_180_HUNDRED: { coinReward: 200, packReward: "TEN" },
  M501_180_TEN: { coinReward: 80, packReward: "SINGLE" },
  M501_180_THREE: { coinReward: 25 },
  M501_180_TWENTY: { coinReward: 200, packReward: "SINGLE" },
  M501_AVG_100: { coinReward: 250, packReward: "FIVE" },
  M501_AVG_105: { coinReward: 300, packReward: "TEN" },
  M501_AVG_110: { coinReward: 350, packReward: "FIVE" },
  M501_AVG_115: { coinReward: 400, packReward: "TEN" },
  M501_AVG_120: { coinReward: 200, packReward: "FIVE" },
  M501_AVG_65: { coinReward: 30 },
  M501_AVG_70: { coinReward: 35 },
  M501_AVG_75: { coinReward: 100, packReward: "SINGLE" },
  M501_AVG_80: { coinReward: 50, packReward: "SINGLE" },
  M501_AVG_85: { coinReward: 60, packReward: "SINGLE" },
  M501_AVG_90: { coinReward: 100, packReward: "FIVE" },
  M501_AVG_95: { coinReward: 125, packReward: "SINGLE" },
  M501_BINGE_10: { coinReward: 250, packReward: "TEN" },
  M501_BINGE_3: { coinReward: 75, packReward: "SINGLE" },
  M501_BINGE_5: { coinReward: 150, packReward: "FIVE" },
  M501_CENTURY_RUNS: { coinReward: 175, packReward: "SINGLE" },
  M501_CHALLENGER_CLEAR: { coinReward: 80, packReward: "SINGLE" },
  M501_CO_FIFTY: { coinReward: 200, packReward: "FIVE" },
  M501_CO_FIVE: { coinReward: 40 },
  M501_CO_HUNDRED: { coinReward: 100, packReward: "SINGLE" },
  M501_CO_RATE: { coinReward: 125, packReward: "FIVE" },
  M501_CO_RATE_60: { coinReward: 150, packReward: "SINGLE" },
  M501_CO_RATE_70: { coinReward: 300, packReward: "FIVE" },
  M501_CO_TEN: { coinReward: 100, packReward: "SINGLE" },
  M501_CO_TWENTYFIVE: { coinReward: 50, packReward: "SINGLE" },
  M501_CO_TWOHUNDRED: { coinReward: 350, packReward: "TEN" },
  M501_DARTS_100: { coinReward: 20 },
  M501_DARTS_1000: { coinReward: 60, packReward: "SINGLE" },
  M501_DARTS_10000: { coinReward: 400, packReward: "FIVE" },
  M501_DARTS_500: { coinReward: 25 },
  M501_DARTS_5000: { coinReward: 175, packReward: "FIVE" },
  M501_FIFTY_RUNS: { coinReward: 75, packReward: "SINGLE" },
  M501_FIRST_180: { coinReward: 30 },
  M501_FIRST_CO: { coinReward: 35 },
  M501_FIRST_WIN: { coinReward: 40 },
  M501_FLAWLESS_5: { coinReward: 80, packReward: "SINGLE" },
  M501_FLAWLESS_9: { coinReward: 200, packReward: "SINGLE" },
  M501_GRAND_PRIX_CLEAR: { coinReward: 100, packReward: "FIVE" },
  M501_GRAND_SLAM: { coinReward: 200, packReward: "TEN" },
  M501_HEAT: { coinReward: 100, packReward: "SINGLE" },
  M501_LAST_GASP: { coinReward: 50, packReward: "SINGLE" },
  M501_LAST_GASP_10: { coinReward: 250, packReward: "FIVE" },
  M501_LAST_GASP_5: { coinReward: 125, packReward: "SINGLE" },
  M501_MARATHON_3: { coinReward: 150, packReward: "FIVE" },
  M501_MATCH_3_180S: { coinReward: 175, packReward: "SINGLE" },
  M501_MATCH_3_CO: { coinReward: 60, packReward: "SINGLE" },
  M501_MATCH_5_180S: { coinReward: 300, packReward: "TEN" },
  M501_MATCH_5_CO: { coinReward: 200, packReward: "FIVE" },
  M501_ON_FIRE: { coinReward: 100, packReward: "SINGLE" },
  M501_PREMIER_CLEAR: { coinReward: 125, packReward: "FIVE" },
  M501_PRO_CLEAR: { coinReward: 75, packReward: "SINGLE" },
  M501_REACH_T2: { coinReward: 20 },
  M501_REACH_T3: { coinReward: 80, packReward: "SINGLE" },
  M501_REACH_T4: { coinReward: 150, packReward: "SINGLE" },
  M501_REACH_T5: { coinReward: 175, packReward: "FIVE" },
  M501_RUNS_200: { coinReward: 200, packReward: "SINGLE" },
  M501_RUNS_25: { coinReward: 25 },
  M501_RUNS_300: { coinReward: 350, packReward: "FIVE" },
  M501_RUNS_500: { coinReward: 400, packReward: "TEN" },
  M501_STREAK_15: { coinReward: 200, packReward: "FIVE" },
  M501_STREAK_2: { coinReward: 30 },
  M501_STREAK_20: { coinReward: 250, packReward: "TEN" },
  M501_STREAK_4: { coinReward: 100, packReward: "SINGLE" },
  M501_STREAK_7: { coinReward: 100, packReward: "FIVE" },
  M501_T1_RUNS_10: { coinReward: 35 },
  M501_T1_RUNS_20: { coinReward: 50, packReward: "SINGLE" },
  M501_T1_RUNS_5: { coinReward: 40 },
  M501_T1_WINS_10: { coinReward: 60, packReward: "SINGLE" },
  M501_T1_WINS_20: { coinReward: 75, packReward: "SINGLE" },
  M501_T1_WINS_5: { coinReward: 20 },
  M501_T2_RUNS_10: { coinReward: 80, packReward: "SINGLE" },
  M501_T2_RUNS_20: { coinReward: 100, packReward: "SINGLE" },
  M501_T2_RUNS_5: { coinReward: 25 },
  M501_T2_WINS_10: { coinReward: 50, packReward: "SINGLE" },
  M501_T2_WINS_20: { coinReward: 125, packReward: "SINGLE" },
  M501_T2_WINS_5: { coinReward: 60, packReward: "SINGLE" },
  M501_T3_RUNS_10: { coinReward: 75, packReward: "SINGLE" },
  M501_T3_RUNS_20: { coinReward: 150, packReward: "FIVE" },
  M501_T3_RUNS_5: { coinReward: 80, packReward: "SINGLE" },
  M501_T3_WINS_10: { coinReward: 175, packReward: "SINGLE" },
  M501_T3_WINS_20: { coinReward: 200, packReward: "FIVE" },
  M501_T3_WINS_5: { coinReward: 100, packReward: "SINGLE" },
  M501_T4_RUNS_10: { coinReward: 125, packReward: "FIVE" },
  M501_T4_RUNS_20: { coinReward: 150, packReward: "SINGLE" },
  M501_T4_RUNS_5: { coinReward: 175, packReward: "FIVE" },
  M501_T4_WINS_10: { coinReward: 200, packReward: "SINGLE" },
  M501_T4_WINS_20: { coinReward: 300, packReward: "FIVE" },
  M501_T4_WINS_5: { coinReward: 100, packReward: "FIVE" },
  M501_T5_RUNS_10: { coinReward: 125, packReward: "SINGLE" },
  M501_T5_RUNS_20: { coinReward: 350, packReward: "TEN" },
  M501_T5_RUNS_5: { coinReward: 150, packReward: "FIVE" },
  M501_T5_WINS_10: { coinReward: 400, packReward: "FIVE" },
  M501_T5_WINS_20: { coinReward: 200, packReward: "TEN" },
  M501_T5_WINS_5: { coinReward: 175, packReward: "SINGLE" },
  M501_TEN_RUNS: { coinReward: 30 },
  M501_UNSTOPPABLE: { coinReward: 250, packReward: "FIVE" },
  M501_WIN_10: { coinReward: 35 },
  M501_WIN_100: { coinReward: 200, packReward: "FIVE" },
  M501_WIN_15: { coinReward: 40 },
  M501_WIN_150: { coinReward: 100, packReward: "SINGLE" },
  M501_WIN_2: { coinReward: 20 },
  M501_WIN_20: { coinReward: 100, packReward: "SINGLE" },
  M501_WIN_200: { coinReward: 300, packReward: "TEN" },
  M501_WIN_25: { coinReward: 50, packReward: "SINGLE" },
  M501_WIN_3: { coinReward: 25 },
  M501_WIN_30: { coinReward: 60, packReward: "SINGLE" },
  M501_WIN_40: { coinReward: 75, packReward: "SINGLE" },
  M501_WIN_5: { coinReward: 30 },
  M501_WIN_50: { coinReward: 80, packReward: "SINGLE" },
  M501_WIN_75: { coinReward: 125, packReward: "FIVE" },
  M501_WIN_T1R1: { coinReward: 35 },
  M501_WIN_T1R2: { coinReward: 40 },
  M501_WIN_T2R1: { coinReward: 20 },
  M501_WIN_T2R2: { coinReward: 100, packReward: "SINGLE" },
  M501_WIN_T3R1: { coinReward: 50, packReward: "SINGLE" },
  M501_WIN_T3R2: { coinReward: 60, packReward: "SINGLE" },
  M501_WIN_T4R1: { coinReward: 150, packReward: "SINGLE" },
  M501_WIN_T4R2: { coinReward: 175, packReward: "FIVE" },
  M501_WIN_T5R1: { coinReward: 200, packReward: "SINGLE" },
  M501_WIN_T5R2: { coinReward: 100, packReward: "FIVE" },
  M501_WORLD_CHAMP: { coinReward: 350, packReward: "FIVE" },
  MARATHON: { coinReward: 125, packReward: "SINGLE" },
  METEOR: { coinReward: 150, packReward: "FIVE" },
  MOMENTUM: { coinReward: 25 },
  MOST_ACTIVE: { coinReward: 75, packReward: "SINGLE" },
  MVP: { coinReward: 400, packReward: "TEN" },
  MYSTIC: { coinReward: 400, packReward: "TEN" },
  NEMESIS_RELATIONSHIP: { coinReward: 80, packReward: "SINGLE" },
  NIGHTMARE: { coinReward: 500, packReward: "TEN" },
  NINE_TO_FIVE_SURVIVOR: { coinReward: 175, packReward: "SINGLE" },
  PAY_DAY: { coinReward: 100, packReward: "SINGLE" },
  PERFECT_RUN: { coinReward: 600, packReward: "TEN" },
  PERFECT_SEASON: { coinReward: 750, packReward: "TEN" },
  PHOENIX: { coinReward: 200, packReward: "FIVE" },
  POINTS_EMPIRE: { coinReward: 200, packReward: "FIVE" },
  POINT_MASTER: { coinReward: 100, packReward: "SINGLE" },
  POINT_THIEF: { coinReward: 1000, packReward: "TEN" },
  PRACTICE_100_PLUS_CHECKOUT_1: { coinReward: 50, packReward: "SINGLE" },
  PRACTICE_100_PLUS_CHECKOUT_10: { coinReward: 250, packReward: "TEN" },
  PRACTICE_100_PLUS_CHECKOUT_5: { coinReward: 125, packReward: "FIVE" },
  PRACTICE_301_WINS_15: { coinReward: 60, packReward: "SINGLE" },
  PRACTICE_301_WINS_30: { coinReward: 150, packReward: "SINGLE" },
  PRACTICE_301_WINS_5: { coinReward: 30 },
  PRACTICE_ALL_CHECKOUTS_100: { coinReward: 400, packReward: "TEN" },
  PRACTICE_ALL_CHECKOUTS_15: { coinReward: 75, packReward: "SINGLE" },
  PRACTICE_ALL_CHECKOUTS_30: { coinReward: 175, packReward: "FIVE" },
  PRACTICE_ALL_CHECKOUTS_5: { coinReward: 35 },
  PRACTICE_ALL_CHECKOUTS_60: { coinReward: 300, packReward: "FIVE" },
  PRACTICE_BEAT_LUCA_3: { coinReward: 80, packReward: "SINGLE" },
  PRACTICE_BEAT_LUKE_3: { coinReward: 100, packReward: "SINGLE" },
  PRACTICE_BEAT_MIKKEL_3: { coinReward: 50, packReward: "SINGLE" },
  PRACTICE_BEAT_PERRY_3: { coinReward: 60, packReward: "SINGLE" },
  PRACTICE_BIG_FISH: { coinReward: 350, packReward: "TEN" },
  PRACTICE_BIG_FISH_5: { coinReward: 500, packReward: "TEN" },
  PRACTICE_BOT_LEVEL_10_WINS_5: { coinReward: 200, packReward: "SINGLE" },
  PRACTICE_BOT_LEVEL_15_WINS_5: { coinReward: 400, packReward: "FIVE" },
  PRACTICE_BOT_LEVEL_20_WINS_5: { coinReward: 600, packReward: "TEN" },
  PRACTICE_BOT_LEVEL_5_WINS_1: { coinReward: 40 },
  PRACTICE_BOT_LEVEL_5_WINS_3: { coinReward: 75, packReward: "SINGLE" },
  PRACTICE_CRICKET_WINS_10: { coinReward: 80, packReward: "SINGLE" },
  PRACTICE_CRICKET_WINS_20: { coinReward: 100, packReward: "FIVE" },
  PRACTICE_CRICKET_WINS_3: { coinReward: 20 },
  PRACTICE_CRICKET_WINS_40: { coinReward: 200, packReward: "TEN" },
  PRACTICE_KILLER_WINS_10: { coinReward: 100, packReward: "SINGLE" },
  PRACTICE_KILLER_WINS_20: { coinReward: 125, packReward: "SINGLE" },
  PRACTICE_KILLER_WINS_3: { coinReward: 25 },
  PRACTICE_PERFECT_SESSION: { coinReward: 250, packReward: "FIVE" },
  PRACTICE_TOTAL_180S_100: { coinReward: 750, packReward: "TEN" },
  PRACTICE_TOTAL_180S_15: { coinReward: 50, packReward: "SINGLE" },
  PRACTICE_TOTAL_180S_30: { coinReward: 150, packReward: "FIVE" },
  PRACTICE_TOTAL_180S_5: { coinReward: 30 },
  PRACTICE_TOTAL_180S_60: { coinReward: 300, packReward: "TEN" },
  PRACTICE_TOTAL_SESSIONS_10: { coinReward: 35 },
  PRACTICE_TOTAL_SESSIONS_100: { coinReward: 350, packReward: "FIVE" },
  PRACTICE_TOTAL_SESSIONS_25: { coinReward: 60, packReward: "SINGLE" },
  PRACTICE_TOTAL_SESSIONS_50: { coinReward: 175, packReward: "SINGLE" },
  PRACTICE_TOTAL_WINS_100: { coinReward: 1000, packReward: "TEN" },
  PRACTICE_TOTAL_WINS_15: { coinReward: 75, packReward: "SINGLE" },
  PRACTICE_TOTAL_WINS_30: { coinReward: 200, packReward: "FIVE" },
  PRACTICE_TOTAL_WINS_5: { coinReward: 40 },
  PRACTICE_TOTAL_WINS_60: { coinReward: 400, packReward: "TEN" },
  PRACTICE_TRIPLE_180_GAME: { coinReward: 100, packReward: "SINGLE" },
  PRACTICE_WIN_STREAK_10: { coinReward: 125, packReward: "FIVE" },
  PRACTICE_WIN_STREAK_3: { coinReward: 20 },
  PRACTICE_WIN_STREAK_5: { coinReward: 80, packReward: "SINGLE" },
  PRACTICE_X01_DOUBLE_OUT_WINS_100: { coinReward: 400, packReward: "TEN" },
  PRACTICE_X01_DOUBLE_OUT_WINS_15: { coinReward: 100, packReward: "SINGLE" },
  PRACTICE_X01_DOUBLE_OUT_WINS_30: { coinReward: 150, packReward: "SINGLE" },
  PRACTICE_X01_DOUBLE_OUT_WINS_5: { coinReward: 25 },
  PRACTICE_X01_DOUBLE_OUT_WINS_60: { coinReward: 200, packReward: "FIVE" },
  PRECISION: { coinReward: 50, packReward: "SINGLE" },
  PREDATOR: { coinReward: 175, packReward: "FIVE" },
  PROFESSIONAL: { coinReward: 60, packReward: "SINGLE" },
  REAPER_SEASONAL: { coinReward: 200, packReward: "SINGLE" },
  RED_HOT: { coinReward: 75, packReward: "SINGLE" },
  REGULAR_PLAYER: { coinReward: 250, packReward: "TEN" },
  REVERSAL: { coinReward: 80, packReward: "SINGLE" },
  RISING_STAR: { coinReward: 100, packReward: "SINGLE" },
  RISK_TAKER: { coinReward: 50, packReward: "SINGLE" },
  RIVALRY_DEFINED: { coinReward: 30 },
  RIVAL_BREAKER: { coinReward: 100, packReward: "FIVE" },
  ROCKET_START: { coinReward: 60, packReward: "SINGLE" },
  ROCK_SOLID: { coinReward: 75, packReward: "SINGLE" },
  SEASON_STARTER: { coinReward: 35 },
  SHARPSHOOTER_ACH: { coinReward: 125, packReward: "SINGLE" },
  SHOCKWAVE: { coinReward: 150, packReward: "FIVE" },
  SHOWMAN: { coinReward: 80, packReward: "SINGLE" },
  SILVER_STANDARD: { coinReward: 100, packReward: "SINGLE" },
  SNAKE: { coinReward: 175, packReward: "SINGLE" },
  SNIPER: { coinReward: 200, packReward: "FIVE" },
  STORM_BRINGER: { coinReward: 100, packReward: "SINGLE" },
  STREAK_MACHINE: { coinReward: 50, packReward: "SINGLE" },
  SUPERSTAR: { coinReward: 300, packReward: "FIVE" },
  SURVIVOR_ACH: { coinReward: 125, packReward: "FIVE" },
  SURVIVOR_ELITE: { coinReward: 350, packReward: "TEN" },
  TACTICAL: { coinReward: 60, packReward: "SINGLE" },
  TARGET_LOCKED: { coinReward: 75, packReward: "SINGLE" },
  THE_HUNTER: { coinReward: 80, packReward: "SINGLE" },
  THREE_O_ONE: { coinReward: 100, packReward: "SINGLE" },
  TKDL_ORIGINAL: { coinReward: 50, packReward: "SINGLE" },
  TOXIC: { coinReward: 150, packReward: "SINGLE" },
  TREBLE_MASTER: { coinReward: 60, packReward: "SINGLE" },
  TWO_HUNDRED: { coinReward: 75, packReward: "SINGLE" },
  UNBEATABLE_VS_ONE: { coinReward: 175, packReward: "FIVE" },
  UNBREAKABLE: { coinReward: 400, packReward: "FIVE" },
  UNDERDOG_SPECIAL: { coinReward: 80, packReward: "SINGLE" },
  UNTOUCHABLE: { coinReward: 500, packReward: "TEN" },
  UNTOUCHABLE_PLUS: { coinReward: 600, packReward: "TEN" },
  VETERAN: { coinReward: 100, packReward: "SINGLE" },
  WARMED_UP: { coinReward: 40 },
  WARPATH: { coinReward: 750, packReward: "TEN" },
  WIN_COLLECTOR: { coinReward: 50, packReward: "SINGLE" },
  WORLD_TOUR: { coinReward: 200, packReward: "SINGLE" },
  'coin-hoarder-1000': { coinReward: 75, packReward: "SINGLE" },
  'coin-hoarder-500': { coinReward: 35, packReward: "SINGLE" },
  'collector-10': { coinReward: 15 },
  'collector-25': { coinReward: 35, packReward: "SINGLE" },
  'collector-50': { coinReward: 75, packReward: "SINGLE" },
  'earned-1000-total': { coinReward: 75, packReward: "SINGLE" },
  'fifty-percent-winrate': { coinReward: 75, packReward: "SINGLE" },
  'fifty-wins': { coinReward: 150, packReward: "FIVE" },
  'first-card': { coinReward: 15 },
  'first-coins': { coinReward: 15 },
  'first-match': { coinReward: 15 },
  'five-wins': { coinReward: 15 },
  'full-collection': { coinReward: 300, packReward: "TEN" },
  'legendary-collector': { coinReward: 150, packReward: "FIVE" },
  'mode-master': { coinReward: 35, packReward: "SINGLE" },
  'perfect-match': { coinReward: 75, packReward: "SINGLE" },
  'practice-pioneer': { coinReward: 15 },
  'rare-master': { coinReward: 75, packReward: "SINGLE" },
  'seven-day-streak': { coinReward: 15 },
  'seventy-percent-winrate': { coinReward: 150, packReward: "FIVE" },
  'ten-wins': { coinReward: 35, packReward: "SINGLE" },
  'thirty-day-streak': { coinReward: 75, packReward: "SINGLE" },
  'twenty-five-wins': { coinReward: 75, packReward: "SINGLE" },
  'win-streak-5': { coinReward: 35, packReward: "SINGLE" },
};

export function getAchievementReward(
  achievementKey: string
): { coinReward?: number; packReward?: 'SINGLE' | 'FIVE' | 'TEN' } {
  return ACHIEVEMENT_REWARDS[achievementKey] || {};
}

export function formatPackReward(packReward?: 'SINGLE' | 'FIVE' | 'TEN'): string {
  if (!packReward) return 'None';
  if (packReward === 'SINGLE') return '1 Pack';
  if (packReward === 'FIVE') return '5-Pack';
  if (packReward === 'TEN') return '10-Pack';
  return 'Unknown';
}
