import { useMemo, useState } from "react";
import { Images, Radio, Sparkles, Trophy } from "lucide-react";
import { useFetch } from "@/hooks/use-fetch";
import { ShareCardButton } from "@/components/ShareCardButton";
import type { ShareCardSpec } from "@/lib/share-card";

type Poster = { id:number; format:string; sideA:string; sideB:string; kicker:string; reason:string|null; level:string; sideAPoints:number|null; sideBPoints:number|null; status:string; winnerName:string|null; matchKey:string|null; seasonName:string|null; createdAt:string };
const ACCENT: Record<string,string> = { Singles:"#ff005c", "Doubles Event":"#0066ff", "Shift Wars":"#22c55e" };

function PosterArtwork({ poster }: { poster: Poster }) {
  const accent = ACCENT[poster.format] ?? "#ff005c";
  return <div className="relative aspect-[1200/630] overflow-hidden rounded-xl border border-white/10 bg-[#070511] p-4 shadow-2xl">
    <div className="absolute inset-0 opacity-60" style={{ background:`radial-gradient(circle at 4% 92%,${accent}55,transparent 38%),radial-gradient(circle at 96% 5%,rgba(0,102,255,.34),transparent 36%),linear-gradient(145deg,#12091b,#040713)` }}/>
    <div className="absolute -right-10 -bottom-20 h-52 w-52 rounded-full border border-white/10 shadow-[0_0_0_24px_rgba(255,255,255,.025),0_0_0_50px_rgba(255,255,255,.015)]"/>
    <div className="relative flex h-full flex-col">
      <div className="flex items-start justify-between gap-3"><div><strong className="font-black uppercase tracking-wider text-white" style={{fontFamily:"Oswald,sans-serif"}}>TKDL<span style={{color:accent}}>LIVE</span></strong><small className="block text-[7px] font-black uppercase tracking-[.18em] text-white/35">Official league graphic</small></div><span className="rounded-full border px-2 py-1 text-[7px] font-black uppercase tracking-wider" style={{color:accent,borderColor:`${accent}66`,background:`${accent}18`}}>{poster.status==="finished"?"Final result":poster.level==="major"?"Major match":"Matchday"}</span></div>
      <div className="my-auto"><small className="font-black uppercase tracking-[.18em]" style={{color:accent,fontFamily:"Oswald,sans-serif"}}>{poster.kicker}</small><div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><strong className="truncate text-left text-xl font-black uppercase sm:text-2xl" style={{fontFamily:"Oswald,sans-serif"}}>{poster.sideA}</strong><b className="grid h-10 w-10 place-items-center rounded-xl border border-[#ffd24a]/40 bg-[#ffd24a]/10 text-sm text-[#ffd24a]" style={{fontFamily:"Oswald,sans-serif"}}>VS</b><strong className="truncate text-right text-xl font-black uppercase sm:text-2xl" style={{fontFamily:"Oswald,sans-serif"}}>{poster.sideB}</strong></div></div>
      <div className="flex items-center justify-between border-t border-white/10 pt-2 text-[7px] font-black uppercase tracking-widest text-white/35"><span>{poster.format}</span><span>{poster.seasonName??"TKDL"}</span></div>
    </div>
  </div>;
}

function posterSpec(p: Poster): ShareCardSpec {
  return { eyebrow:p.kicker, title:`${p.sideA} vs ${p.sideB}`, versus:{sideA:p.sideA,sideB:p.sideB}, subtitle:p.status==="finished"&&p.winnerName?`${p.winnerName} won · ${p.reason??"Result confirmed"}`:p.reason??"Next on the oche", badge:p.status==="finished"?"Final Result":p.level==="major"?"Major Match":"Official Match Poster", accent:ACCENT[p.format]??"#ff005c", secondaryAccent:"#0066ff", stats:[{label:"Side A",value:p.sideAPoints!=null?`${p.sideAPoints} pts`:p.sideA},{label:"Competition",value:p.format},{label:"Side B",value:p.sideBPoints!=null?`${p.sideBPoints} pts`:p.sideB}], footer:`${p.seasonName??"TKDL"} · ${new Date(p.createdAt).toLocaleDateString("en-GB")}` };
}

export default function PosterLibrary() {
  const { data, loading } = useFetch<Poster[]>("/api/match-posters");
  const [season,setSeason] = useState("all"), [format,setFormat] = useState("all");
  const seasons = useMemo(() => [...new Set((data??[]).map(x=>x.seasonName).filter((x):x is string=>Boolean(x)))], [data]);
  const items = (data??[]).filter(x => (season==="all"||x.seasonName===season)&&(format==="all"||x.format===format));
  const finals = (data??[]).filter(x=>x.status==="finished").length;
  return <div className="space-y-5">
    <header className="relative overflow-hidden rounded-2xl p-6 sm:p-8" style={{border:"1px solid rgba(255,210,74,.22)",background:"radial-gradient(circle at 85% 10%,rgba(0,102,255,.2),transparent 35%),linear-gradient(135deg,rgba(255,0,92,.13),rgba(8,5,18,.96))"}}><div className="absolute -right-16 -top-24 h-72 w-72 rounded-full border border-white/5 shadow-[0_0_0_32px_rgba(255,255,255,.02),0_0_0_68px_rgba(255,255,255,.012)]"/><div className="relative"><span className="flex items-center gap-2 text-xs font-black uppercase tracking-[.16em] text-[#ffd24a]" style={{fontFamily:"Oswald,sans-serif"}}><Images className="h-4 w-4"/>TKDL Media Archive</span><h1 className="mb-2 mt-3 font-black uppercase" style={{fontFamily:"Oswald,sans-serif",fontSize:"clamp(2.4rem,7vw,5rem)",lineHeight:.9}}>Match Poster<br/><em className="not-italic text-[#ff005c]">Library</em></h1><p className="m-0 max-w-2xl text-white/45">Every Matchday graphic, presented as a media wall and ready to preview, share or download again.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white/45">{data?.length??0} posters</span><span className="rounded-full border border-[#ffd24a]/20 bg-[#ffd24a]/5 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-[#ffd24a]">{finals} final results</span></div></div></header>
    <div className="flex flex-wrap items-center gap-2 rounded-xl border border-white/5 bg-white/[.02] p-3"><Sparkles className="h-4 w-4 text-[#ffd24a]"/><select value={season} onChange={e=>setSeason(e.target.value)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-white"><option value="all">All seasons</option>{seasons.map(x=><option key={x}>{x}</option>)}</select><select value={format} onChange={e=>setFormat(e.target.value)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-white"><option value="all">All competitions</option>{["Singles","Doubles Event","Shift Wars"].map(x=><option key={x}>{x}</option>)}</select><span className="ml-auto text-xs text-white/30">Showing {items.length}</span></div>
    {loading ? <div className="p-10 text-center text-white/40">Loading poster archive…</div> : items.length===0 ? <div className="pdc-card p-10 text-center text-white/35">No posters have been created for this selection yet.</div> : <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map(p=><article key={p.id} className="group rounded-2xl border border-white/10 bg-white/[.025] p-3 transition-transform hover:-translate-y-1" style={{boxShadow:`0 22px 55px ${ACCENT[p.format]??"#ff005c"}0c`}}><PosterArtwork poster={p}/><div className="px-1 pb-1 pt-3"><div className="flex justify-between gap-3"><span className="text-xs font-black uppercase" style={{color:ACCENT[p.format]??"#ff005c",fontFamily:"Oswald,sans-serif"}}>{p.kicker}</span><small className="text-white/30">{new Date(p.createdAt).toLocaleDateString("en-GB")}</small></div><p className="min-h-8 text-xs text-white/35">{p.status==="finished"&&p.winnerName?`${p.winnerName} won. `:""}{p.reason}</p><div className="mt-3 flex items-center justify-between gap-2"><span className="flex items-center gap-1 text-[10px] font-black uppercase text-white/30"><Radio className="h-3 w-3"/>{p.format}</span><ShareCardButton spec={posterSpec(p)} filename={`${p.sideA}-vs-${p.sideB}-${p.id}`} label="Open poster"/></div>{p.matchKey&&<a href={`/match-centre/${p.matchKey}`} className="mt-3 flex items-center gap-1 text-xs font-black uppercase text-[#ffd24a]"><Trophy className="h-3 w-3"/>Open result</a>}</div></article>)}</div>}
  </div>;
}
