import { useMemo, useState } from "react";
import { Images, Radio, Trophy } from "lucide-react";
import { useFetch } from "@/hooks/use-fetch";
import { ShareCardButton } from "@/components/ShareCardButton";

type Poster={id:number;format:string;sideA:string;sideB:string;kicker:string;reason:string|null;level:string;sideAPoints:number|null;sideBPoints:number|null;status:string;winnerName:string|null;matchKey:string|null;seasonName:string|null;createdAt:string};
const ACCENT:Record<string,string>={Singles:"#ff005c","Doubles Event":"#0066ff","Shift Wars":"#22c55e"};

export default function PosterLibrary(){
  const {data,loading}=useFetch<Poster[]>("/api/match-posters");
  const [season,setSeason]=useState("all"),[format,setFormat]=useState("all");
  const seasons=useMemo(()=>[...new Set((data??[]).map(x=>x.seasonName).filter((x):x is string=>Boolean(x)))],[data]);
  const items=(data??[]).filter(x=>(season==="all"||x.seasonName===season)&&(format==="all"||x.format===format));
  return <div className="space-y-5"><header className="rounded-2xl p-6 sm:p-8" style={{border:"1px solid rgba(255,210,74,.22)",background:"radial-gradient(circle at 85% 10%,rgba(0,102,255,.2),transparent 35%),linear-gradient(135deg,rgba(255,0,92,.13),rgba(8,5,18,.96))"}}><span className="flex items-center gap-2 uppercase font-black text-xs" style={{color:"#ffd24a",letterSpacing:".16em",fontFamily:"Oswald,sans-serif"}}><Images className="w-4 h-4"/>TKDL Media Archive</span><h1 className="mt-3 mb-2 uppercase font-black" style={{fontFamily:"Oswald,sans-serif",fontSize:"clamp(2.4rem,7vw,5rem)",lineHeight:.9}}>Match Poster<br/><em style={{color:"#ff005c",fontStyle:"normal"}}>Library</em></h1><p className="m-0 max-w-2xl" style={{color:"rgba(255,255,255,.42)"}}>Every poster created through Matchday, preserved by season and ready to share again at full resolution.</p></header>
    <div className="flex gap-2 flex-wrap"><select value={season} onChange={e=>setSeason(e.target.value)} className="rounded-lg px-3 py-2 bg-black/30 border border-white/10 text-white"><option value="all">All seasons</option>{seasons.map(x=><option key={x}>{x}</option>)}</select><select value={format} onChange={e=>setFormat(e.target.value)} className="rounded-lg px-3 py-2 bg-black/30 border border-white/10 text-white"><option value="all">All competitions</option>{["Singles","Doubles Event","Shift Wars"].map(x=><option key={x}>{x}</option>)}</select></div>
    {loading?<div className="p-10 text-center text-white/40">Loading poster archive…</div>:items.length===0?<div className="pdc-card p-10 text-center text-white/35">No posters have been created for this selection yet.</div>:<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{items.map(p=>{const spec={eyebrow:p.kicker,title:`${p.sideA} vs ${p.sideB}`,versus:{sideA:p.sideA,sideB:p.sideB},subtitle:p.status==="finished"&&p.winnerName?`${p.winnerName} won · ${p.reason??"Result confirmed"}`:p.reason??"Next on the oche",badge:p.status==="finished"?"Final Result":p.level==="major"?"Major Match":"Official Match Poster",accent:ACCENT[p.format]??"#ff005c",secondaryAccent:"#0066ff",stats:[{label:"Side A",value:p.sideAPoints!=null?`${p.sideAPoints} pts`:p.sideA},{label:"Competition",value:p.format},{label:"Side B",value:p.sideBPoints!=null?`${p.sideBPoints} pts`:p.sideB}],footer:`${p.seasonName??"TKDL"} · ${new Date(p.createdAt).toLocaleDateString("en-GB")}`};return <article key={p.id} className="rounded-2xl p-4" style={{border:`1px solid ${ACCENT[p.format]??"#ff005c"}35`,background:"rgba(255,255,255,.025)"}}><div className="flex justify-between gap-3"><span className="uppercase font-black text-xs" style={{color:ACCENT[p.format]??"#ff005c",fontFamily:"Oswald,sans-serif"}}>{p.kicker}</span><small className="text-white/30">{new Date(p.createdAt).toLocaleDateString("en-GB")}</small></div><h2 className="uppercase font-black text-2xl mt-5 mb-1" style={{fontFamily:"Oswald,sans-serif"}}>{p.sideA}<span style={{color:"#ffd24a"}}> vs </span>{p.sideB}</h2><p className="text-xs text-white/35 min-h-8">{p.status==="finished"&&p.winnerName?`${p.winnerName} won. `:""}{p.reason}</p><div className="flex items-center justify-between gap-2 mt-4"><span className="flex items-center gap-1 text-[10px] uppercase font-black text-white/30"><Radio className="w-3 h-3"/>{p.format}</span><ShareCardButton spec={spec} filename={`${p.sideA}-vs-${p.sideB}-${p.id}`} label="Create again"/></div>{p.matchKey&&<a href={`/match-centre/${p.matchKey}`} className="flex items-center gap-1 mt-3 text-xs font-black uppercase" style={{color:"#ffd24a"}}><Trophy className="w-3 h-3"/>Open result</a>}</article>})}</div>}
  </div>;
}
