import { Router, type IRouter } from "express";
import healthRouter        from "./health";
import playersRouter       from "./players";
import matchesRouter       from "./matches";
import seasonsRouter       from "./seasons";
import leaderboardRouter   from "./leaderboard";
import achievementsRouter  from "./achievements";
import statsRouter         from "./stats";
import adminRouter         from "./admin";
import authRouter          from "./auth";
import settingsRouter      from "./settings";
import gameTypesRouter     from "./game-types";
import practiceRouter      from "./practice";
import teamMatchesRouter   from "./team-matches";
import tourRouter          from "./tour";
import master501Router     from "./master501";
import storageRouter       from "./storage";
import communityRouter     from "./community";
import messagesRouter      from "./messages";
import notificationsRouter from "./notifications";
import statsDetailedRouter from "./stats-detailed";
import cardClashRouter     from "./card-clash";
import challengesRouter    from "./challenges";
import practiceModeRouter  from "./practice-mode";
import cardClashSettingsRouter from "./card-clash-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(playersRouter);
router.use(matchesRouter);
router.use(teamMatchesRouter);
router.use(seasonsRouter);
router.use(leaderboardRouter);
router.use(achievementsRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(settingsRouter);
router.use(gameTypesRouter);
router.use(practiceRouter);
router.use(tourRouter);
router.use(master501Router);
router.use(storageRouter);
router.use(communityRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(statsDetailedRouter);
router.use("/card-clash", cardClashRouter);
router.use("/challenges", challengesRouter);
router.use(practiceModeRouter);
router.use(cardClashSettingsRouter);

export default router;
