/**
 * UNIFIED CARD DEFINITIONS - Phase 2 Fix
 * 
 * All 100 cards with consistent naming between seed and TSX components.
 * Card IDs map to artwork files in /card-artwork/ (converted to kebab-case)
 * Rarities: COMMON (75%), RARE (20%), LEGENDARY (5%)
 * 
 * Counts:
 * - X01 GOOD: 20 cards (6 Common, 8 Rare, 6 Legendary)
 * - X01 BAD: 20 cards (6 Common, 8 Rare, 6 Legendary)  
 * - CRICKET GOOD: 20 cards (6 Common, 8 Rare, 6 Legendary)
 * - CRICKET BAD: 20 cards (6 Common, 8 Rare, 6 Legendary)
 * - WILDCARD GOOD: 10 cards (0 Common, 5 Rare, 5 Legendary)
 * - WILDCARD BAD: 10 cards (0 Common, 5 Rare, 5 Legendary)
 */

export interface CardDefinition {
  id: string; // unique identifier (e.g., "x01g01")
  name: string; // display name, matches TSX component name
  gameMode: "X01" | "Cricket" | "Wildcard";
  type: "GOOD" | "BAD";
  rarity: "COMMON" | "RARE" | "LEGENDARY";
  effect: string; // game effect description
  flavourText: string; // flavor text for card back
  energyCost: number; // card energy cost (0-3)
  artworkUrl: string; // URL to individual card artwork
}

function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2") // camelCase to kebab-case
    .replace(/([0-9])([A-Z])/g, "$1-$2") // handle numbers
    .toLowerCase();
}

export const ALL_CARDS_UNIFIED: CardDefinition[] = [
  // ========== X01 GOOD (20 cards) ==========
  {
    id: "x01g01",
    name: "BankingStrategy",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Gain +5 points on scores 20-39",
    flavourText: "Smart money stays in play",
    energyCost: 1,
    artworkUrl: "/card-artwork/banking-strategy.jpg",
  },
  {
    id: "x01g02",
    name: "BigGamePlayer",
    gameMode: "X01",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Double points on finishing throws",
    flavourText: "Thrives under pressure",
    energyCost: 3,
    artworkUrl: "/card-artwork/big-game-player.jpg",
  },
  {
    id: "x01g03",
    name: "CenturyMaker",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Bonus +15 when scoring 100+",
    flavourText: "100 is just the beginning",
    energyCost: 1,
    artworkUrl: "/card-artwork/century-maker.jpg",
  },
  {
    id: "x01g04",
    name: "CheckoutConfidence",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "+10 points when within 20 of finish",
    flavourText: "Trust your finishing",
    energyCost: 2,
    artworkUrl: "/card-artwork/checkout-confidence.jpg",
  },
  {
    id: "x01g05",
    name: "CheckoutSpecialist",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "Cannot bust on checkout attempts",
    flavourText: "Master of the finish",
    energyCost: 2,
    artworkUrl: "/card-artwork/checkout-specialist.jpg",
  },
  {
    id: "x01g06",
    name: "CloseControl",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "Reduce opponent's next score by 10",
    flavourText: "Dictate the pace",
    energyCost: 2,
    artworkUrl: "/card-artwork/close-control.jpg",
  },
  {
    id: "x01g07",
    name: "ExactFinish",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "Exact score wins immediately",
    flavourText: "Perfect calculation",
    energyCost: 3,
    artworkUrl: "/card-artwork/exact-finish.jpg",
  },
  {
    id: "x01g08",
    name: "FinishingBonus",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "+20 points per checkout attempt",
    flavourText: "Finish with flair",
    energyCost: 2,
    artworkUrl: "/card-artwork/finishing-bonus.jpg",
  },
  {
    id: "x01g09",
    name: "HighPressure",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Gain +3 per throw under 50 away",
    flavourText: "Thrive on the wire",
    energyCost: 1,
    artworkUrl: "/card-artwork/high-pressure.jpg",
  },
  {
    id: "x01g10",
    name: "HighRoller",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "+25 on any 180",
    flavourText: "Maximum damage",
    energyCost: 2,
    artworkUrl: "/card-artwork/high-roller.jpg",
  },
  {
    id: "x01g11",
    name: "IronWill",
    gameMode: "X01",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Ignore opponent's next penalty",
    flavourText: "Unshakeable resolve",
    energyCost: 3,
    artworkUrl: "/card-artwork/iron-will.jpg",
  },
  {
    id: "x01g12",
    name: "PerfectRhythm",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+2 per consecutive throw in same zone",
    flavourText: "Find your groove",
    energyCost: 1,
    artworkUrl: "/card-artwork/perfect-rhythm.jpg",
  },
  {
    id: "x01g13",
    name: "PowerSurge50",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "Triple next 50 zone hit",
    flavourText: "Maximum treble power",
    energyCost: 2,
    artworkUrl: "/card-artwork/power-surge-50.jpg",
  },
  {
    id: "x01g14",
    name: "PrecisionStrike",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "Guaranteed accuracy next throw",
    flavourText: "Surgical precision",
    energyCost: 2,
    artworkUrl: "/card-artwork/precision-strike.jpg",
  },
  {
    id: "x01g15",
    name: "SafetyBoost",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Cannot bust this turn",
    flavourText: "Play it safe",
    energyCost: 1,
    artworkUrl: "/card-artwork/safety-boost.jpg",
  },
  {
    id: "x01g16",
    name: "SafetyNet",
    gameMode: "X01",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Catch opponent's next bust",
    flavourText: "Save them from themselves",
    energyCost: 3,
    artworkUrl: "/card-artwork/safety-net.jpg",
  },
  {
    id: "x01g17",
    name: "ScoringArsenal",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+5 all zone hits this turn",
    flavourText: "Armed and ready",
    energyCost: 1,
    artworkUrl: "/card-artwork/scoring-arsenal.jpg",
  },
  {
    id: "x01g18",
    name: "SteadyHand",
    gameMode: "X01",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "+10 all throws this turn",
    flavourText: "Nerves of steel",
    energyCost: 3,
    artworkUrl: "/card-artwork/steady-hand.jpg",
  },
  {
    id: "x01g19",
    name: "TrebleBoost",
    gameMode: "X01",
    type: "GOOD",
    rarity: "RARE",
    effect: "+15 on all treble hits",
    flavourText: "Maximum multiplier",
    energyCost: 2,
    artworkUrl: "/card-artwork/treble-boost.jpg",
  },
  {
    id: "x01g20",
    name: "TrebleHunter",
    gameMode: "X01",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Next treble worth double",
    flavourText: "Hunt the wire",
    energyCost: 1,
    artworkUrl: "/card-artwork/treble-hunter.jpg",
  },

  // ========== X01 BAD (20 cards) ==========
  {
    id: "x01b01",
    name: "BrickWall",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "Opponent gains +20 this turn",
    flavourText: "Immovable object",
    energyCost: 1,
    artworkUrl: "/card-artwork/brick-wall.jpg",
  },
  {
    id: "x01b02",
    name: "ClutchBreaker",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "-15 on all finishing throws",
    flavourText: "Crumble under pressure",
    energyCost: 2,
    artworkUrl: "/card-artwork/clutch-breaker.jpg",
  },
  {
    id: "x01b03",
    name: "DeadZone",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Cannot score in outer single ring",
    flavourText: "The scoring void",
    energyCost: 2,
    artworkUrl: "/card-artwork/dead-zone.jpg",
  },
  {
    id: "x01b04",
    name: "DoublesDontCount",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Double zone hits score as single",
    flavourText: "Halved finish zone",
    energyCost: 2,
    artworkUrl: "/card-artwork/doubles-don-t-count.jpg",
  },
  {
    id: "x01b05",
    name: "Fatigue",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "-5 per throw this turn",
    flavourText: "Energy drained",
    energyCost: 2,
    artworkUrl: "/card-artwork/fatigue.jpg",
  },
  {
    id: "x01b06",
    name: "FinishDelay",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Extend game by 2 additional points",
    flavourText: "The grind continues",
    energyCost: 2,
    artworkUrl: "/card-artwork/finish-delay.jpg",
  },
  {
    id: "x01b07",
    name: "Jinx",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Next throw busts if not exact",
    flavourText: "Cursed throw",
    energyCost: 2,
    artworkUrl: "/card-artwork/jinx.jpg",
  },
  {
    id: "x01b08",
    name: "LegReset",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Restart the game from 501",
    flavourText: "Back to square one",
    energyCost: 3,
    artworkUrl: "/card-artwork/leg-reset.jpg",
  },
  {
    id: "x01b09",
    name: "Lockdown",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Cannot change scoring zone next turn",
    flavourText: "Stuck in one place",
    energyCost: 2,
    artworkUrl: "/card-artwork/lockdown.jpg",
  },
  {
    id: "x01b10",
    name: "LowBlow",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "-10 on all throws this turn",
    flavourText: "Below the belt",
    energyCost: 1,
    artworkUrl: "/card-artwork/low-blow.jpg",
  },
  {
    id: "x01b11",
    name: "MentalBlock",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "Cannot score over 100 this turn",
    flavourText: "Psychological warfare",
    energyCost: 1,
    artworkUrl: "/card-artwork/mental-block.jpg",
  },
  {
    id: "x01b12",
    name: "MercyKiller",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "Opponent cannot finish this turn",
    flavourText: "No mercy",
    energyCost: 1,
    artworkUrl: "/card-artwork/mercy-killer.jpg",
  },
  {
    id: "x01b13",
    name: "OffTarget",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "Next throw misses scoring zone",
    flavourText: "Wild shot",
    energyCost: 1,
    artworkUrl: "/card-artwork/off-target.jpg",
  },
  {
    id: "x01b14",
    name: "PressureZone",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "-3 per throw under 50 away",
    flavourText: "Choking zone",
    energyCost: 1,
    artworkUrl: "/card-artwork/pressure-zone.jpg",
  },
  {
    id: "x01b15",
    name: "RustHands40",
    gameMode: "X01",
    type: "BAD",
    rarity: "COMMON",
    effect: "-15 on all throws under 40",
    flavourText: "Rusty accuracy",
    energyCost: 1,
    artworkUrl: "/card-artwork/rust-hands-40.jpg",
  },
  {
    id: "x01b16",
    name: "Shackled",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Lose one turn",
    flavourText: "Trapped and helpless",
    energyCost: 2,
    artworkUrl: "/card-artwork/shackled.jpg",
  },
  {
    id: "x01b17",
    name: "Trapped",
    gameMode: "X01",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Skip next 2 turns",
    flavourText: "Completely imprisoned",
    energyCost: 3,
    artworkUrl: "/card-artwork/trapped.jpg",
  },
  {
    id: "x01b18",
    name: "TrebleCurse",
    gameMode: "X01",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Treble hits score as single",
    flavourText: "The wire abandons you",
    energyCost: 3,
    artworkUrl: "/card-artwork/treble-curse.jpg",
  },
  {
    id: "x01b19",
    name: "TurnEnforcer",
    gameMode: "X01",
    type: "BAD",
    rarity: "RARE",
    effect: "Cannot pass turn early",
    flavourText: "Forced to throw",
    energyCost: 2,
    artworkUrl: "/card-artwork/turn-enforcer.jpg",
  },
  {
    id: "x01b20",
    name: "WildThrow",
    gameMode: "X01",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Random dart lands (0-180 points)",
    flavourText: "Chaos incarnate",
    energyCost: 3,
    artworkUrl: "/card-artwork/wild-throw.jpg",
  },

  // ========== CRICKET GOOD (20 cards) ==========
  {
    id: "cg01",
    name: "BullMultiplier",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "Bulls score triple marks",
    flavourText: "The heart of the target",
    energyCost: 2,
    artworkUrl: "/card-artwork/bull-multiplier.jpg",
  },
  {
    id: "cg02",
    name: "BullseyeRush",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "+1 mark on bulls per throw",
    flavourText: "Charging at the center",
    energyCost: 2,
    artworkUrl: "/card-artwork/bullseye-rush.jpg",
  },
  {
    id: "cg03",
    name: "ClosingProtection",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Closed numbers cannot be reopened",
    flavourText: "Seal the deal",
    energyCost: 1,
    artworkUrl: "/card-artwork/closing-protection.jpg",
  },
  {
    id: "cg04",
    name: "ComebackMarks",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+2 marks on comeback attempts",
    flavourText: "Second chance wins",
    energyCost: 1,
    artworkUrl: "/card-artwork/comeback-marks.jpg",
  },
  {
    id: "cg05",
    name: "Dominance",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Score points while closing numbers",
    flavourText: "Overwhelming presence",
    energyCost: 3,
    artworkUrl: "/card-artwork/dominance.jpg",
  },
  {
    id: "cg06",
    name: "DoubleStrike",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "Double zone hits close 2 marks",
    flavourText: "Double power",
    energyCost: 2,
    artworkUrl: "/card-artwork/double-strike.jpg",
  },
  {
    id: "cg07",
    name: "EarlyCloser",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+1 mark on first 5 rounds",
    flavourText: "Start strong",
    energyCost: 1,
    artworkUrl: "/card-artwork/early-closer.jpg",
  },
  {
    id: "cg08",
    name: "HighScorer",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Points double on high numbers (20, 25, 50)",
    flavourText: "Hunt the big zones",
    energyCost: 1,
    artworkUrl: "/card-artwork/high-scorer.jpg",
  },
  {
    id: "cg09",
    name: "InstantMark",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "First throw always marks its number",
    flavourText: "Instant hits",
    energyCost: 2,
    artworkUrl: "/card-artwork/instant-mark.jpg",
  },
  {
    id: "cg10",
    name: "MarkAccelerator",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "+1 mark per consecutive number",
    flavourText: "Building momentum",
    energyCost: 2,
    artworkUrl: "/card-artwork/mark-accelerator.jpg",
  },
  {
    id: "cg11",
    name: "MarkFlood",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Single zone hits close 2 marks",
    flavourText: "Overwhelming force",
    energyCost: 3,
    artworkUrl: "/card-artwork/mark-flood.jpg",
  },
  {
    id: "cg12",
    name: "MarkMultiplier",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "Triple zone marks count as 3",
    flavourText: "Maximum damage",
    energyCost: 2,
    artworkUrl: "/card-artwork/mark-multiplier.jpg",
  },
  {
    id: "cg13",
    name: "MomentumArsenal",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "+1 mark per closed number",
    flavourText: "Building arsenal",
    energyCost: 2,
    artworkUrl: "/card-artwork/momentum-arsenal.jpg",
  },
  {
    id: "cg14",
    name: "NumberResurrection",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "Reopen one opponent's closed number",
    flavourText: "Second life",
    energyCost: 1,
    artworkUrl: "/card-artwork/number-resurrection.jpg",
  },
  {
    id: "cg15",
    name: "PerfectForm",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Perfect throws count as 3 marks",
    flavourText: "Flawless execution",
    energyCost: 3,
    artworkUrl: "/card-artwork/perfect-form.jpg",
  },
  {
    id: "cg16",
    name: "PerfectRound",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+1 mark if all 3 darts same number",
    flavourText: "Perfect harmony",
    energyCost: 1,
    artworkUrl: "/card-artwork/perfect-round.jpg",
  },
  {
    id: "cg17",
    name: "QuickClose",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "Close numbers in 2 marks instead of 3",
    flavourText: "Efficient closing",
    energyCost: 2,
    artworkUrl: "/card-artwork/quick-close.jpg",
  },
  {
    id: "cg18",
    name: "ScoringMomentum",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "COMMON",
    effect: "+5 points per mark this turn",
    flavourText: "Building points",
    energyCost: 1,
    artworkUrl: "/card-artwork/scoring-momentum.jpg",
  },
  {
    id: "cg19",
    name: "ScoringSurge",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "+10 points per mark this turn",
    flavourText: "Points explosion",
    energyCost: 3,
    artworkUrl: "/card-artwork/scoring-surge.jpg",
  },
  {
    id: "cg20",
    name: "SniperLock",
    gameMode: "Cricket",
    type: "GOOD",
    rarity: "RARE",
    effect: "Lock opponent into specific number",
    flavourText: "Locked on target",
    energyCost: 2,
    artworkUrl: "/card-artwork/sniper-lock.jpg",
  },

  // ========== CRICKET BAD (20 cards) ==========
  {
    id: "cb01",
    name: "AimShift",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Next throw shifts to random number",
    flavourText: "Lost focus",
    energyCost: 1,
    artworkUrl: "/card-artwork/aim-shift.jpg",
  },
  {
    id: "cb02",
    name: "BadAim",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Miss target half the darts",
    flavourText: "Wayward throws",
    energyCost: 1,
    artworkUrl: "/card-artwork/bad-aim.jpg",
  },
  {
    id: "cb03",
    name: "BullVoid",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Bull zone is void (no marks)",
    flavourText: "Bullseye blocked",
    energyCost: 2,
    artworkUrl: "/card-artwork/bull-void.jpg",
  },
  {
    id: "cb04",
    name: "ClosingBlocker",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Cannot close numbers this turn",
    flavourText: "Doors sealed shut",
    energyCost: 1,
    artworkUrl: "/card-artwork/closing-blocker.jpg",
  },
  {
    id: "cb05",
    name: "CricketPrison",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Stuck on current number for 2 turns",
    flavourText: "Trapped in the numbers",
    energyCost: 2,
    artworkUrl: "/card-artwork/cricket-prison.jpg",
  },
  {
    id: "cb06",
    name: "Distraction",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "-1 mark per throw this turn",
    flavourText: "Lose focus",
    energyCost: 1,
    artworkUrl: "/card-artwork/distraction.jpg",
  },
  {
    id: "cb07",
    name: "Hesitation",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Half all marks this turn",
    flavourText: "Uncertainty strikes",
    energyCost: 2,
    artworkUrl: "/card-artwork/hesitation.jpg",
  },
  {
    id: "cb08",
    name: "MarkDrain",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "-2 marks from one closed number",
    flavourText: "Progress stolen",
    energyCost: 2,
    artworkUrl: "/card-artwork/mark-drain.jpg",
  },
  {
    id: "cb09",
    name: "MarkErasure",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Erase 1 mark from a number",
    flavourText: "Progress reversed",
    energyCost: 2,
    artworkUrl: "/card-artwork/mark-erasure.jpg",
  },
  {
    id: "cb10",
    name: "MarkKiller",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Close opponent's active number",
    flavourText: "Ruthless counter",
    energyCost: 2,
    artworkUrl: "/card-artwork/mark-killer.jpg",
  },
  {
    id: "cb11",
    name: "MomentumKiller",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Negate all marks this turn",
    flavourText: "Momentum shattered",
    energyCost: 3,
    artworkUrl: "/card-artwork/momentum-killer-cricket.jpg",
  },
  {
    id: "cb12",
    name: "NumberHex",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Curse a number (no marks next turn)",
    flavourText: "Hexed zone",
    energyCost: 1,
    artworkUrl: "/card-artwork/number-hex.jpg",
  },
  {
    id: "cb13",
    name: "NumberPrison",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Lock opponent into specific number",
    flavourText: "Number prison",
    energyCost: 1,
    artworkUrl: "/card-artwork/number-prison.jpg",
  },
  {
    id: "cb14",
    name: "OutOfPosition",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "Random zone hit (cannot control)",
    flavourText: "Loss of control",
    energyCost: 1,
    artworkUrl: "/card-artwork/out-of-position.jpg",
  },
  {
    id: "cb15",
    name: "PenaltyZone",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "COMMON",
    effect: "-5 points per mark this turn",
    flavourText: "Punishing zone",
    energyCost: 1,
    artworkUrl: "/card-artwork/penalty-zone.jpg",
  },
  {
    id: "cb16",
    name: "Pressure",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Lose 1 turn",
    flavourText: "Overwhelmed",
    energyCost: 2,
    artworkUrl: "/card-artwork/pressure.jpg",
  },
  {
    id: "cb17",
    name: "ReOpeningBlock",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Cannot reopen closed numbers",
    flavourText: "Permanently sealed",
    energyCost: 2,
    artworkUrl: "/card-artwork/re-opening-block.jpg",
  },
  {
    id: "cb18",
    name: "ScoreHalve",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "RARE",
    effect: "Halve all points this turn",
    flavourText: "Points lost",
    energyCost: 2,
    artworkUrl: "/card-artwork/score-halve.jpg",
  },
  {
    id: "cb19",
    name: "SluggyMarks",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "All marks count as 0 this turn",
    flavourText: "Heavy fog",
    energyCost: 3,
    artworkUrl: "/card-artwork/sluggish-marks.jpg",
  },
  {
    id: "cb20",
    name: "StreakBreaker",
    gameMode: "Cricket",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Reset opponent's momentum",
    flavourText: "Streak ended",
    energyCost: 3,
    artworkUrl: "/card-artwork/streak-breaker.jpg",
  },

  // ========== WILDCARD GOOD (10 cards) ==========
  {
    id: "wg01",
    name: "CoinFlip",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "50% double points or half points",
    flavourText: "Leave it to chance",
    energyCost: 2,
    artworkUrl: "/card-artwork/coin-flip.jpg",
  },
  {
    id: "wg02",
    name: "ComebackLeg",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Restore 50 points and momentum",
    flavourText: "Revival from ashes",
    energyCost: 3,
    artworkUrl: "/card-artwork/comeback-leg.jpg",
  },
  {
    id: "wg03",
    name: "FinishingEdge",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "+50 on finishing throws",
    flavourText: "The perfect finish",
    energyCost: 2,
    artworkUrl: "/card-artwork/finishing-edge.jpg",
  },
  {
    id: "wg04",
    name: "HotHand",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "+10 per consecutive hits",
    flavourText: "In the zone",
    energyCost: 2,
    artworkUrl: "/card-artwork/hot-hand.jpg",
  },
  {
    id: "wg05",
    name: "Invincible",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Immune to all effects this turn",
    flavourText: "Unstoppable force",
    energyCost: 3,
    artworkUrl: "/card-artwork/invincible.jpg",
  },
  {
    id: "wg06",
    name: "LuckyStreak",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "+20 random bonus this turn",
    flavourText: "Fortune smiles",
    energyCost: 2,
    artworkUrl: "/card-artwork/lucky-streak.jpg",
  },
  {
    id: "wg07",
    name: "MatchPoint",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Convert lead into instant win",
    flavourText: "Victory is yours",
    energyCost: 3,
    artworkUrl: "/card-artwork/match-point.jpg",
  },
  {
    id: "wg08",
    name: "MomentumSurge",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "Triple next throw damage",
    flavourText: "Unstoppable wave",
    energyCost: 2,
    artworkUrl: "/card-artwork/momentum-surge.jpg",
  },
  {
    id: "wg09",
    name: "PerfectGame",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "LEGENDARY",
    effect: "Treat all throws as perfect",
    flavourText: "Perfection achieved",
    energyCost: 3,
    artworkUrl: "/card-artwork/perfect-game.jpg",
  },
  {
    id: "wg10",
    name: "Underdog",
    gameMode: "Wildcard",
    type: "GOOD",
    rarity: "RARE",
    effect: "+30 bonus when behind",
    flavourText: "Never count us out",
    energyCost: 2,
    artworkUrl: "/card-artwork/underdog.jpg",
  },

  // ========== WILDCARD BAD (10 cards) ==========
  {
    id: "wb01",
    name: "DarkCloud",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "All throws miss next turn",
    flavourText: "Shadow falls",
    energyCost: 2,
    artworkUrl: "/card-artwork/dark-cloud.jpg",
  },
  {
    id: "wb02",
    name: "Hex",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "Reverse all bonuses next turn",
    flavourText: "Dark magic",
    energyCost: 2,
    artworkUrl: "/card-artwork/hex.jpg",
  },
  {
    id: "wb03",
    name: "MatchPressure",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Opponent wins if they lead",
    flavourText: "Final pressure",
    energyCost: 3,
    artworkUrl: "/card-artwork/match-pressure.jpg",
  },
  {
    id: "wb04",
    name: "MomentumKillerWildcard",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Reset all bonuses and effects",
    flavourText: "Complete shutdown",
    energyCost: 3,
    artworkUrl: "/card-artwork/momentum-killer-wildcard.jpg",
  },
  {
    id: "wb05",
    name: "Shutdown",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "Skip next 2 turns",
    flavourText: "Systems offline",
    energyCost: 2,
    artworkUrl: "/card-artwork/shutdown.jpg",
  },
  {
    id: "wb06",
    name: "TotalAnnihilation",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Lose 50 points randomly",
    flavourText: "Complete destruction",
    energyCost: 3,
    artworkUrl: "/card-artwork/total-annihilation.jpg",
  },
  {
    id: "wb07",
    name: "UndogCurse",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "-30 penalty when ahead",
    flavourText: "Curse of the underdog",
    energyCost: 2,
    artworkUrl: "/card-artwork/underdog-curse.jpg",
  },
  {
    id: "wb08",
    name: "UnluckyNight",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "Random -50 point loss",
    flavourText: "Luck runs out",
    energyCost: 2,
    artworkUrl: "/card-artwork/unlucky-night.jpg",
  },
  {
    id: "wb09",
    name: "WinBonusRemoved",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "RARE",
    effect: "Negate all win bonuses",
    flavourText: "Victory stripped away",
    energyCost: 2,
    artworkUrl: "/card-artwork/win-bonus-removed.jpg",
  },
  {
    id: "wb10",
    name: "Wipeout",
    gameMode: "Wildcard",
    type: "BAD",
    rarity: "LEGENDARY",
    effect: "Lose all progress this match",
    flavourText: "Everything is lost",
    energyCost: 3,
    artworkUrl: "/card-artwork/wipeout.jpg",
  },
];

// Export for backwards compatibility
export const ALL_CARDS = ALL_CARDS_UNIFIED;
