export interface CardSeed {
  name: string;
  gameMode: "X01" | "CRICKET" | "WILDCARD";
  type: "GOOD" | "BAD";
  rarity: "COMMON" | "RARE" | "LEGENDARY";
  effect: string;
}

export const ALL_CARDS_UNIFIED: CardSeed[] = [
  // ── X01 GOOD (20) ──────────────────────────────────────────────────────────
  { name: "Big Game Player",      gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "If you score 80+ (not on double), gain +35 bonus next leg." },
  { name: "Power Surge +50",      gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "Add +50 to your turn total." },
  { name: "Treble Hunter",        gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "Next treble hit counts at 1.3x — T20 becomes 78 instead of 60." },
  { name: "Unstoppable Checkout", gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "While on double, opponent cannot play penalty cards this turn." },
  { name: "Banking Strategy",     gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "If you score 50+ (not on double), next turn gets +20 bonus." },
  { name: "Checkout Confidence",  gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "If on double, gain 1 free re-throw if you miss the first attempt." },
  { name: "Exact Finish",         gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "In final 50 points, if you hit your double, opponent can't play penalty cards next turn." },
  { name: "High Pressure",        gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "If opponent is ahead in legs, gain +40 bonus this leg." },
  { name: "Perfect Rhythm",       gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "All your darts this turn score +10 each." },
  { name: "High Roller",          gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "If you score over 100 this turn, gain +25 bonus." },
  { name: "Precision Strike",     gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "Your next three darts score minimum 6 — no 1–5 segments this turn." },
  { name: "Safety Boost",         gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "Your lowest-value dart this turn scores minimum +15." },
  { name: "Treble Boost",         gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "Your trebles count at 1.4x this turn — T20 becomes 84 instead of 60." },
  { name: "Safety Net",           gameMode: "X01", type: "GOOD", rarity: "LEGENDARY", effect: "If you would bust, score half your current visit total instead." },
  { name: "Close Control",        gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "In final 50 points, any dart that would bust is automatically reduced to 1 point." },
  { name: "Steady Hand",          gameMode: "X01", type: "GOOD", rarity: "LEGENDARY", effect: "Your darts can't miss the board — any complete miss is redirected to segment 5." },
  { name: "Scoring Arsenal",      gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "Your turn can't end until all 3 darts are thrown — forces a full visit." },
  { name: "Finishing Bonus",      gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "If you finish this turn, gain +50 bonus points." },
  { name: "Century Maker",        gameMode: "X01", type: "GOOD", rarity: "COMMON",    effect: "If you score exactly 100 this turn, gain +40 bonus." },
  { name: "Iron Will",            gameMode: "X01", type: "GOOD", rarity: "RARE",      effect: "All your darts score at 1.2x value this turn." },

  // ── X01 BAD (20) ───────────────────────────────────────────────────────────
  { name: "Rust Hands -40",       gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Target's next turn score is reduced by 40 points." },
  { name: "Wild Throw",           gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "One random dart this turn becomes a complete miss — 0 points." },
  { name: "Brick Wall",           gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target can't score on 20, 19, or 18 (any ring) this turn." },
  { name: "Low Blow",             gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Single hits count as 0 — only doubles and trebles score." },
  { name: "Doubles Don't Count",  gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Doubles count as singles this turn — D20 = 20, not 40." },
  { name: "Shackled",             gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Target's highest possible dart this turn is capped at 50." },
  { name: "Turn Enforcer",        gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target must complete all 3 darts before attempting to finish." },
  { name: "Pressure Zone",        gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Target can only score on 15, 20, or Bull — all other segments score 0." },
  { name: "Off Target",           gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target's darts shift to the adjacent dartboard segment — 20 becomes 1 or 5." },
  { name: "Mercy Killer",         gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Target's turn is capped at 60 total." },
  { name: "Jinx",                 gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "All target's darts score at 0.75x value this turn." },
  { name: "Fatigue",              gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target's darts get progressively worse — Dart 1 normal, Dart 2 x0.9, Dart 3 x0.8." },
  { name: "Leg Reset",            gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "If target won 2+ legs in a row, their streak is reset to zero." },
  { name: "Clutch Breaker",       gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "In final 100 points, target's darts score -15 each." },
  { name: "Finish Delay",         gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target's first 2 darts can't finish — doubles count as singles until dart 3." },
  { name: "Treble Curse",         gameMode: "X01", type: "BAD", rarity: "LEGENDARY", effect: "Trebles count as singles this turn — T20 = 20, not 60." },
  { name: "Dead Zone",            gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target can't score on any segment 15-20 this turn — only 1-14 and Bull." },
  { name: "Mental Block",         gameMode: "X01", type: "BAD", rarity: "COMMON",    effect: "Each dart thrown costs 10 points — visit length x10 is subtracted." },
  { name: "Trapped",              gameMode: "X01", type: "BAD", rarity: "RARE",      effect: "Target must finish on double or their turn ends immediately after 1 dart." },
  { name: "Lockdown",             gameMode: "X01", type: "BAD", rarity: "LEGENDARY", effect: "Choose one segment — target can only score on that number all turn." },

  // ── CRICKET GOOD (20) ──────────────────────────────────────────────────────
  { name: "Instant Mark",         gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "Automatically mark the called number without throwing — counts as 1 hit." },
  { name: "Double Strike",        gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "Your marks count as 2x toward opening or closing this turn." },
  { name: "Sniper Lock",          gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "Next 3 darts must hit the called number — any miss scores 0." },
  { name: "Number Resurrection",  gameMode: "CRICKET", type: "GOOD", rarity: "LEGENDARY", effect: "One closed number becomes fresh and reopenable again — opponent's marks reset." },
  { name: "Scoring Surge",        gameMode: "CRICKET", type: "GOOD", rarity: "LEGENDARY", effect: "All your open numbers score at 1.5x value this leg — T20 = 90 instead of 60." },
  { name: "Closing Protection",   gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "Once you open a number, opponent can't close it this leg." },
  { name: "Mark Flood",           gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "All your darts this turn automatically mark — even if you miss the number." },
  { name: "Scoring Momentum",     gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "Each mark this turn is worth +5 more points than the last." },
  { name: "Early Closer",         gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "If you close a number before turn 5, get +30 bonus points." },
  { name: "Perfect Round",        gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "If all 3 darts mark this turn, gain +25 bonus." },
  { name: "Bull Multiplier",      gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "When you hit Bull, it counts as marking any 3 numbers you choose." },
  { name: "Bullseye Rush",        gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "Bull = auto-marks 2 numbers of your choice." },
  { name: "Comeback Marks",       gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "If you're behind in points, all your marks count at 1.5x toward opening." },
  { name: "Mark Accelerator",     gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "When you hit the called number, marks count as 2 — closing twice as fast." },
  { name: "Mark Multiplier",      gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "If you mark the called number 3+ times this turn, score +50 bonus points." },
  { name: "Quick Close",          gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "If you close your number by dart 2, get a free mark on the next number." },
  { name: "Momentum Arsenal",     gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "Each successful mark builds +10 point bonus — stacks through the turn." },
  { name: "High Scorer",          gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "If you score 100+ points this turn, gain +20 bonus." },
  { name: "Perfect Form",         gameMode: "CRICKET", type: "GOOD", rarity: "RARE",      effect: "All your marks count this turn AND you score at 1.5x." },
  { name: "Dominance",            gameMode: "CRICKET", type: "GOOD", rarity: "COMMON",    effect: "If you lead in closed numbers, all your marks are worth 1.3x." },

  // ── CRICKET BAD (20) ───────────────────────────────────────────────────────
  { name: "Bad Aim",              gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Target's marks count at 50% value toward opening or closing." },
  { name: "Distraction",          gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target loses their next number mark completely — hit doesn't count." },
  { name: "Out of Position",      gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Target can't hit high-value numbers — 20, 19, 18 all score 0 this turn." },
  { name: "Penalty Zone",         gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target's next marks must be on 6-15 only — high numbers and Bull don't mark." },
  { name: "Re-Opening Block",     gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "When you close one of target's numbers, that number is permanently locked." },
  { name: "Aim Shift",            gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target's shots hit adjacent segments — 20 to 1/5, 19 to 3/7." },
  { name: "Hesitation",           gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Target's first dart this turn doesn't mark — only darts 2 and 3 count." },
  { name: "Pressure",             gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target must close their current number or lose 30 points at turn end." },
  { name: "Momentum Killer",      gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "If target had 2+ marks last turn, they lose those marks this turn." },
  { name: "Sluggish Marks",       gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "All target's marks count as 1 this turn — regardless of single, double, or treble." },
  { name: "Number Hex",           gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target is locked to one number all turn — any other segment scores 0." },
  { name: "Closing Blocker",      gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Target cannot close any numbers this turn — marks cap at 2." },
  { name: "Mark Erasure",         gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Each mark costs target 10 points — marks still count, but -10 each." },
  { name: "Cricket Prison",       gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Target can only hit 15, 19, 20 — only 3 of the 7 cricket numbers mark." },
  { name: "Bull Void",            gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "Bull doesn't count as marking anything this turn." },
  { name: "Mark Killer",          gameMode: "CRICKET", type: "BAD", rarity: "COMMON",    effect: "Target's final dart this turn doesn't count as a mark." },
  { name: "Mark Drain",           gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "If target leads in points, they lose 1 mark from a random opened number each turn." },
  { name: "Streak Breaker",       gameMode: "CRICKET", type: "BAD", rarity: "RARE",      effect: "If target had 3+ marks last turn, lose half those marks this turn." },
  { name: "Number Prison",        gameMode: "CRICKET", type: "BAD", rarity: "LEGENDARY", effect: "One random closed number is locked forever — target can never reopen it." },
  { name: "Score Halve",          gameMode: "CRICKET", type: "BAD", rarity: "LEGENDARY", effect: "Target's open numbers score at 0.5x value this leg — T20 = 30 instead of 60." },

  // ── WILDCARD GOOD (10) ─────────────────────────────────────────────────────
  { name: "Coin Flip",       gameMode: "WILDCARD", type: "GOOD", rarity: "RARE",      effect: "50/50 chance — either gain +40 bonus OR opponent loses 30 points." },
  { name: "Lucky Streak",    gameMode: "WILDCARD", type: "GOOD", rarity: "COMMON",    effect: "If you won the previous leg, gain +50 bonus this leg." },
  { name: "Momentum Surge",  gameMode: "WILDCARD", type: "GOOD", rarity: "COMMON",    effect: "If you're ahead in the match, gain +25 bonus this leg." },
  { name: "Finishing Edge",  gameMode: "WILDCARD", type: "GOOD", rarity: "RARE",      effect: "In the final deciding leg, if you miss a finish or close attempt, you get 1 free retry." },
  { name: "Comeback Leg",    gameMode: "WILDCARD", type: "GOOD", rarity: "RARE",      effect: "If you lost the previous leg, gain +60 bonus this leg." },
  { name: "Hot Hand",        gameMode: "WILDCARD", type: "GOOD", rarity: "RARE",      effect: "If you've won 2+ legs in a row, gain +45 bonus." },
  { name: "Underdog",        gameMode: "WILDCARD", type: "GOOD", rarity: "COMMON",    effect: "If you're behind overall, gain +50 bonus this leg." },
  { name: "Perfect Game",    gameMode: "WILDCARD", type: "GOOD", rarity: "COMMON",    effect: "If this is a shutout leg (opponent scored 0), gain +30 bonus." },
  { name: "Match Point",     gameMode: "WILDCARD", type: "GOOD", rarity: "LEGENDARY", effect: "If you're 1 leg away from winning the match, gain +70 bonus." },
  { name: "Invincible",      gameMode: "WILDCARD", type: "GOOD", rarity: "LEGENDARY", effect: "Your next turn is completely unaffected by any opponent penalty cards." },

  // ── WILDCARD BAD (10) ──────────────────────────────────────────────────────
  { name: "Dark Cloud",         gameMode: "WILDCARD", type: "BAD", rarity: "COMMON",    effect: "Target's next leg score reduced by 35 points (X01) or 1 number locked (Cricket)." },
  { name: "Momentum Killer",    gameMode: "WILDCARD", type: "BAD", rarity: "RARE",      effect: "Remove any momentum or streak bonus target had — reset their consecutive wins." },
  { name: "Unlucky Night",      gameMode: "WILDCARD", type: "BAD", rarity: "COMMON",    effect: "All target's darts count at 75% value this leg." },
  { name: "Hex",                gameMode: "WILDCARD", type: "BAD", rarity: "RARE",      effect: "All target's darts count at 50% value (X01) or marks at 50% (Cricket) this leg." },
  { name: "Wipeout",            gameMode: "WILDCARD", type: "BAD", rarity: "RARE",      effect: "Target's last 2 darts this leg score 0." },
  { name: "Total Annihilation", gameMode: "WILDCARD", type: "BAD", rarity: "LEGENDARY", effect: "Target's next leg score reduced by 100 OR loses 1 opened number — whichever game mode." },
  { name: "Match Pressure",     gameMode: "WILDCARD", type: "BAD", rarity: "RARE",      effect: "In the final leg of the match, target's darts score -20 each (X01) or marks halved (Cricket)." },
  { name: "Underdog Curse",     gameMode: "WILDCARD", type: "BAD", rarity: "COMMON",    effect: "If target is ahead, all their darts score at 0.8x value." },
  { name: "Win Bonus Removed",  gameMode: "WILDCARD", type: "BAD", rarity: "COMMON",    effect: "If target won last leg, they lose that momentum bonus." },
  { name: "Shutdown",           gameMode: "WILDCARD", type: "BAD", rarity: "RARE",      effect: "Target's leg capped at 50 points (X01) or 2 numbers max (Cricket)." },
];

export { ALL_CARDS_UNIFIED as ALL_CARDS };
